import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @serwist/next from src/app/sw.ts at build time — not
    // source, and its minified/worker-scoped code isn't meant to satisfy
    // the app's own lint rules.
    "public/sw.js",
    // Native Capacitor projects (see MOBILE.md) — `cap sync` copies
    // public/ (including the generated sw.js above) into both, plus
    // Xcode/Gradle project files that aren't app source at all.
    "ios/**",
    "android/**",
    // Playwright's own generated output (HTML report + trace viewer
    // bundles, raw test artifacts) — not app source, and its minified
    // bundled JS isn't meant to satisfy the app's lint rules either.
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
