import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @serwist/next from src/app/sw.ts at build time — not
    // source, and its minified/worker-scoped code isn't meant to satisfy
    // the app's own lint rules.
    "public/sw.js",
  ]),
]);

export default eslintConfig;
