/**
 * Названия тематических блоков экзамена, по-русски.
 *
 * ЧТО ЭТО И ЧЕМ ОНО НЕ ЯВЛЯЕТСЯ. У блока экзамена (`ExamSkillArea`) одно
 * поле `title` на обе локали, и на `/ru` оно показывалось по-испански —
 * тот же класс, что `Story.author` (долг 34) и названия самих экзаменов
 * (7.129). Замер 06.09.2026: блоков в содержимом **139**, различных
 * названий 138, русских вариантов в данных **0 из 139**.
 *
 * Таблица переводит ТОЛЬКО при точном совпадении ключа. Название, которого
 * здесь нет, проходит насквозь неизменным — и это не запас прочности, а
 * половина правила: экзамен можно переписать через `/admin/exams`, и имя,
 * данное человеком, обязано печататься как есть, а не подменяться
 * выдуманным переводом. Ровно то же правило и та же оговорка, что у
 * `localizeStoryAuthor`.
 *
 * Ключ — испанское название БЕЗ скобочного хвоста со ссылкой на уроки:
 * хвост («(lección 7)», «(lecciones 1-2)», «(lección 29 y nivel A2
 * completo)») — это шаблон, он живёт в словарях, а не здесь, потому что
 * иначе одна и та же тема лежала бы в таблице по нескольку раз с разными
 * номерами уроков.
 *
 * В базу НИЧЕГО не пишется: `content.json` и таблица `Exam` не тронуты.
 * Испанская сторона не меняется ни на знак — `localizeSkillAreaTitle`
 * возвращает исходное значение при `lang === "es"` первой же строкой.
 *
 * Опечатка, которую таблица НЕ чинит: в испанском ключе про уступки стоит
 * «несмотря на то que» — русское начало с испанским «que» на конце. Это
 * данные, и правка тронула бы `/es`; ключ поэтому воспроизводит опечатку
 * буква в букву, а русское значение написано правильно.
 */
export const SKILL_AREA_TITLES_RU: Record<string, string> = {
  "Alfabeto y pronunciación": "Алфавит и произношение",
  "Saludos y presentación personal": "Приветствия и знакомство",
  "Los casos rusos: primera introducción": "Русские падежи: первое знакомство",
  "Números, precios y la hora": "Числа, цены и время",
  "En el restaurante y en la tienda": "В ресторане и в магазине",
  "La familia y las descripciones simples": "Семья и простые описания",
  "Verbos en presente: primera conjugación": "Глаголы настоящего времени: первое спряжение",
  "Orientarse en la ciudad": "Ориентация в городе",
  "Modo imperativo: dar órdenes y consejos": "Повелительное наклонение: приказы и советы",
  "Verbos modales: querer y poder": "Модальные глаголы: хотеть и мочь",
  "Caso preposicional: lugares (где?)": "Предложный падеж: места (где?)",
  "Medios de transporte (на чём?)": "Виды транспорта (на чём?)",
  "Caso acusativo: objeto directo (что?/кого?)": "Винительный падеж: прямое дополнение (что?/кого?)",
  "Caso acusativo: dirección (куда?)": "Винительный падеж: направление (куда?)",
  "El pasado de los verbos": "Прошедшее время глаголов",
  "El futuro: perfectivo e imperfectivo": "Будущее время: совершенный и несовершенный вид",
  "La construcción «у меня есть» (tener)": "Конструкция «у меня есть» (обладание)",
  "La hora y las partes del día": "Время и части суток",
  "Los días de la semana y los meses": "Дни недели и месяцы",
  "Fechas: ¿qué fecha es hoy?": "Даты: какое сегодня число?",
  "Alfabeto y saludos": "Алфавит и приветствия",
  "Género gramatical, casos y números": "Грамматический род, падежи и числа",
  "Pedir, querer y poder": "Просить, хотеть и мочь",
  "Familia y adjetivos": "Семья и прилагательные",
  "Verbos en presente": "Глаголы настоящего времени",
  "En la ciudad: imperativo y direcciones": "В городе: повелительное наклонение и дорога",
  "Caso preposicional y transporte": "Предложный падеж и транспорт",
  "Caso acusativo: objeto y dirección": "Винительный падеж: дополнение и направление",
  "Pasado, futuro y aspecto verbal": "Прошедшее, будущее и вид глагола",
  "Posesión, hora y calendario": "Обладание, время и календарь",
  "Caso genitivo: ausencia, cantidad y origen": "Родительный падеж: отсутствие, количество и происхождение",
  "Caso dativo: edad y sentimientos": "Дательный падеж: возраст и чувства",
  "Caso instrumental: profesiones y compañía": "Творительный падеж: профессии и совместность",
  "Diálogos de viaje: restaurante, hotel, calle y aeropuerto": "Диалоги в поездке: ресторан, гостиница, улица и аэропорт",
  "Aspecto verbal: imperfectivo y perfectivo": "Вид глагола: несовершенный и совершенный",
  "El pasado y el futuro en profundidad": "Прошедшее и будущее время подробно",
  "Genitivo y acusativo en la práctica": "Родительный и винительный падежи на практике",
  "El clima y las estaciones": "Погода и времена года",
  "Planes de viaje y transporte público": "Планы поездки и общественный транспорт",
  "La casa, el barrio y las direcciones": "Дом, район и как объяснить дорогу",
  "Comparaciones y opiniones simples": "Сравнения и простые мнения",
  "Salud y el cuerpo humano": "Здоровье и тело человека",
  "Genitivo de adjetivos y pronombres": "Родительный падеж прилагательных и местоимений",
  "Dativo de adjetivos y pronombres, y repaso integrador": "Дательный падеж прилагательных и местоимений и обобщающее повторение",
  "Instrumental de adjetivos y pronombres": "Творительный падеж прилагательных и местоимений",
  "Casos después de preposiciones complejas": "Падежи после сложных предлогов",
  "Repaso general: todos los casos en un texto": "Общее повторение: все падежи в одном тексте",
  "Verbos de movimiento: идти y ходить": "Глаголы движения: идти и ходить",
  "Verbos de movimiento: ехать y ездить": "Глаголы движения: ехать и ездить",
  "Verbos de movimiento: бежать y бегать": "Глаголы движения: бежать и бегать",
  "Otros verbos de movimiento: летать, плавать, носить": "Другие глаголы движения: летать, плавать, носить",
  "Verbos de movimiento: síntesis y práctica": "Глаголы движения: обобщение и практика",
  "Grado comparativo de los adjetivos: más allá de lo básico": "Сравнительная степень прилагательных: сверх основ",
  "Grado comparativo de los adverbios y repaso integrador": "Сравнительная степень наречий и обобщающее повторение",
  "Aspecto verbal, pasado y futuro": "Вид глагола, прошедшее и будущее время",
  "Casos en la práctica: genitivo y acusativo": "Падежи на практике: родительный и винительный",
  "Clima, estaciones y transporte": "Погода, времена года и транспорт",
  "La casa, el barrio y la salud": "Дом, район и здоровье",
  "Genitivo, dativo e instrumental de adjetivos y pronombres": "Родительный, дательный и творительный падежи прилагательных и местоимений",
  "Preposiciones complejas y repaso general de casos": "Сложные предлоги и общее повторение падежей",
  "Verbos de movimiento: seis pares y sus prefijos": "Глаголы движения: шесть пар и их приставки",
  "Grado comparativo, superlativo e igualdad": "Сравнительная и превосходная степень и равенство",
  "Pronombres indefinidos: -то y -нибудь/-либо": "Неопределённые местоимения: -то и -нибудь/-либо",
  "Pronombres y adverbios negativos": "Отрицательные местоимения и наречия",
  "La visita al médico y la farmacia": "Визит к врачу и аптека",
  "De compras: ropa y devoluciones": "Покупки: одежда и возврат товара",
  "Clima, orientación en la ciudad y repaso integrador": "Погода, ориентация в городе и обобщающее повторение",
  "Describir el carácter y el aspecto físico": "Описание характера и внешности",
  "Conectores lógicos: causa, consecuencia y concesión": "Логические связки: причина, следствие и уступка",
  "Dativo e instrumental en contexto": "Дательный и творительный падежи в контексте",
  "Expresar opiniones y estar de acuerdo o en desacuerdo": "Выражение мнения, согласие и несогласие",
  "El mundo laboral y los estudios": "Работа и учёба",
  "Narrar experiencias pasadas con detalle": "Подробный рассказ о прошлом",
  "Medios de comunicación y noticias sencillas": "Средства массовой информации и простые новости",
  "Cultura y costumbres rusas": "Русская культура и обычаи",
  "Escribir correos y mensajes formales": "Письма и официальные сообщения",
  "Verbos de movimiento con prefijo при-/у-: llegar y partir": "Глаголы движения с приставками при-/у-: прибытие и уход",
  "Verbos de movimiento con prefijo в-/вы-: entrar y salir, y repaso integrador": "Глаголы движения с приставками в-/вы-: вход и выход, и обобщающее повторение",
  "Verbos de movimiento con prefijo под-/от-: acercarse y alejarse": "Глаголы движения с приставками под-/от-: приближение и удаление",
  "Verbos de movimiento con prefijo пере-: cruzar y trasladarse": "Глаголы движения с приставкой пере-: пересечение и переезд",
  "Verbos de movimiento con prefijo про-/до-: pasar de largo y llegar hasta": "Глаголы движения с приставками про-/до-: пройти мимо и дойти до",
  "Verbos de movimiento con prefijos: repaso y significados figurados": "Глаголы движения с приставками: повторение и переносные значения",
  "Aspecto verbal en pasado: perfectivo e imperfectivo": "Вид глагола в прошедшем времени: совершенный и несовершенный",
  "Aspecto verbal en futuro: perfectivo e imperfectivo": "Вид глагола в будущем времени: совершенный и несовершенный",
  "Aspecto del infinitivo tras verbos modales": "Вид инфинитива после модальных глаголов",
  "Aspecto verbal en la negación y la repetición": "Вид глагола при отрицании и повторяемости",
  "Participios activos: presente y pasado": "Действительные причастия: настоящего и прошедшего времени",
  "Participios pasivos: presente y pasado, y repaso integrador": "Страдательные причастия: настоящего и прошедшего времени, и обобщающее повторение",
  "Conectores lógicos y casos dativo/instrumental en contexto": "Логические связки и дательный с творительным падежи в контексте",
  "Expresar opiniones y el mundo laboral/estudios": "Выражение мнения, работа и учёба",
  "Conectores narrativos y medios de comunicación": "Связки повествования и средства массовой информации",
  "Cultura rusa y correspondencia formal": "Русская культура и официальная переписка",
  "Verbos de movimiento con prefijos при-/у-, в-/вы-": "Глаголы движения с приставками при-/у-, в-/вы-",
  "Verbos de movimiento con prefijos под-/от-, пере-": "Глаголы движения с приставками под-/от-, пере-",
  "Verbos de movimiento про-/до- y repaso figurado": "Глаголы движения про-/до- и повторение переносных значений",
  "Aspecto verbal en pasado y futuro": "Вид глагола в прошедшем и будущем времени",
  "Aspecto del infinitivo tras modales, negación y repetición": "Вид инфинитива после модальных глаголов, при отрицании и повторяемости",
  "Participios activos y pasivos": "Действительные и страдательные причастия",
  "Gerundios imperfectivos y perfectivos": "Деепричастия несовершенного и совершенного вида",
  "Discurso indirecto: что, чтобы y preguntas indirectas": "Косвенная речь: что, чтобы и косвенные вопросы",
  "Oraciones de relativo con который: declinación completa": "Придаточные с «который»: полное склонение",
  "Entrevista de trabajo, educación, cine/libros y exclamaciones": "Собеседование, образование, кино и книги, восклицания",
  "Repaso integrador de todo el nivel B1": "Обобщающее повторение всего уровня B1",
  "El condicional/subjuntivo con «бы»": "Сослагательное наклонение с «бы»",
  "Condicionales reales: «если... то...»": "Реальное условие: «если... то...»",
  "Registro de debate formal: argumentar y contraargumentar": "Регистр официальной дискуссии: доводы и возражения",
  "Ruso literario: figuras estilísticas y orden invertido": "Литературный русский: стилистические фигуры и инверсия",
  "Modismos y lenguaje coloquial": "Идиомы и разговорная речь",
  "Temas de actualidad y sociedad": "Актуальные темы и общество",
  "Ruso profesional y de negocios": "Профессиональный и деловой русский",
  "Adjetivos cortos y declinación de numerales": "Краткие прилагательные и склонение числительных",
  "Participios sustituyendo oraciones con «который»": "Причастия вместо придаточных с «который»",
  "Gerundios sustituyendo subordinadas y repaso integrador": "Деепричастия вместо придаточных и обобщающее повторение",
  "Estilo y matices en participios y gerundios": "Стиль и оттенки причастий и деепричастий",
  "Participios activos vs. cláusulas con «который»": "Действительные причастия против придаточных с «который»",
  "Participios pasivos en el registro escrito formal": "Страдательные причастия в официальном письменном стиле",
  "Causales neutras: «потому что», «так как», «поскольку»": "Нейтральные причинные союзы: «потому что», «так как», «поскольку»",
  "Concesivas: «несмотря на то que», «хотя», «вопреки»": "Уступительные конструкции: «несмотря на то что», «хотя», «вопреки»",
  "Causa valorativa: «благодаря», «из-за», «в связи с»": "Оценочная причина: «благодаря», «из-за», «в связи с»",
  "Finales y consecutivas: «для того чтобы», «так что»": "Цель и следствие: «для того чтобы», «так что»",
  "Verbos de movimiento en sentido figurado I": "Глаголы движения в переносном значении I",
  "Verbos de movimiento en sentido figurado II": "Глаголы движения в переносном значении II",
  "Idiomatismos con verbos de movimiento y repaso integrador": "Идиомы с глаголами движения и обобщающее повторение",
  "Condicional irreal (бы) y condicional real (если...то)": "Нереальное условие (бы) и реальное условие (если...то)",
  "Debate formal y estilo literario": "Официальная дискуссия и литературный стиль",
  "Registro coloquial y temas de actualidad y sociedad": "Разговорный регистр, актуальные темы и общество",
  "Ruso profesional y de negocios; adjetivos cortos y numerales": "Профессиональный и деловой русский; краткие прилагательные и числительные",
  "Participios y gerundios: mecánica de sustitución": "Причастия и деепричастия: механика замены",
  "Densidad de registro y elección который vs. participio": "Плотность регистра и выбор: «который» или причастие",
  "Participios pasivos cortos y conjunciones causales neutras": "Краткие страдательные причастия и нейтральные причинные союзы",
  "Concesivas y conectores causales valorativos": "Уступительные конструкции и оценочные причинные связки",
  "Finales/consecutivas y verbos de movimiento en sentido figurado I": "Цель и следствие, глаголы движения в переносном значении I",
  "Verbos de movimiento en sentido figurado II e idiomatismos": "Глаголы движения в переносном значении II и идиомы",
  "Modismos gramaticales avanzados y estilo científico": "Продвинутые грамматические обороты и научный стиль",
  "Correspondencia oficial y estilo periodístico": "Официальная переписка и публицистический стиль",
  "Transformación de registro y persuasión/modalidad de opinión": "Смена регистра и убеждение: модальность мнения",
  "Ecología, tecnología y crítica cultural": "Экология, технологии и культурная критика",
  "Ironía, matices y repaso integrador de todo el nivel B2": "Ирония, оттенки смысла и обобщающее повторение всего уровня B2",
};
