import type { MetadataRoute } from "next";

// Next.js Metadata Route convention — served automatically at
// /manifest.webmanifest, no manual JSON file or extra dependency needed.
// Icons generated by scripts/generate-pwa-icons.ts from the same sparkle
// glyph as BrandMark.tsx (src/components/lesson/BrandMark.tsx).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "RusoFásil",
    short_name: "RusoFásil",
    description: "Cursos de ruso para hispanohablantes, del nivel A1 al B2.",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#3730a3",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
