import type { MetadataRoute } from "next";

import { SITE_BRAND } from "@/lib/brand";

// Next.js Metadata Route convention — served automatically at
// /manifest.webmanifest, no manual JSON file or extra dependency needed.
// Icons generated by scripts/generate-pwa-icons.ts from the same matryoshka
// mark as BrandMark.tsx/MatryoshkaMark.tsx.
export default function manifest(): MetadataRoute.Manifest {
  return {
    // Бренд САЙТА, не витринное имя приложения: под иконкой в App Store и
    // Google Play стоит «RusoFácil» (короче, долг 70 «б»), а установленный
    // с сайта PWA остаётся сайтом и подписывается его брендом. Значение
    // берётся из src/lib/brand.ts — единственного места, где оно
    // объявлено для кода.
    name: SITE_BRAND,
    short_name: SITE_BRAND,
    description: "Ruso para hispanohablantes: curso A1–B2; vocabulario, cuentos y juegos hasta C1.",
    start_url: "/",
    display: "standalone",
    background_color: "#fff8ec",
    theme_color: "#2d5f8a",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
