// The WORD_SEARCH rungs prisma/redistribute-word-search.ts re-lays — on a
// board of a different size, and across more boards when one is not
// enough — plus the tail sequences the leftovers live in.
//
// Three groups, in the order they were decided (all of them stay here
// forever, applied or not — see `applied`):
//   ·  20 — разгрузка по порогу 80%/3 (PROGRESS 7.83), записаны 02.09;
//   ·  40 — сорок худших по коридору (PROGRESS 7.86), записаны 02.09;
//   · 124 — порция 1 коридора (PROGRESS 7.101), записаны 03.09;
//   ·  20 — пилот порции 2 (PROGRESS 7.105), записан 04.09;
//   · 401 — остаток порции 2 (PROGRESS 7.107), записан 04.09.
//
// ONE manifest, read by two scripts that must agree:
//
//  · prisma/redistribute-word-search.ts writes these rows (the data PR).
//  · prisma/generate-word-games.ts must NOT overwrite them on its next
//    full run, and must not delete the tail as "stale" either — its
//    cleanup pass deletes every sequence past the ladder's computed max,
//    and the tail is by construction past it.
//
// Why the rungs are pinned here rather than recomputed as "the worst ten"
// at run time: the redistribution runs against production, and a list
// that recomputes itself is a list nobody can review before it writes.
// The numbers below were measured ON PRODUCTION on 2026-09-02 by
// prisma/build-density-manifest.ts — see PROGRESS.md 7.83.
//
// НИ ОДНА запись не трогает рунг из бесплатной десятки (sequence <= 10
// при уровне не C1). Это не свойство отбора «так вышло», а инвариант со
// своим тестом (density-rungs.test.ts), и держится он на двух разных
// причинах сразу: такие рунги тематические (topics.ts), и деление
// сломало бы обещание заголовка; и они же — единственные, чей
// `updatedAt` попадает в <lastmod> sitemap.xml, то есть единственные,
// после которых файл перестаёт быть побайтово тем же. Набор URL в
// sitemap при этом не меняется никогда: он выведен из констант
// (free-tier.ts), а не из базы, и хвостовые номера все далеко за 10.
import type { FlashcardLevel } from "@/lib/flashcards/types";

export interface DensitySplit {
  level: FlashcardLevel;
  /** The rung that is over-packed. Regenerated IN PLACE — same row id,
   * same URL, same WordGameProgress. */
  sequence: number;
  /** Total grids the words end up in, including the one above. */
  parts: number;
  /** Стороны сеток, по одной на часть, в том же порядке: первая — сторона
   * строки-источника, остальные — хвостовых строк. Размер доски теперь
   * ВЫБИРАЕТСЯ под длину слов и целевую занятость (quality.ts), а не
   * наследуется, поэтому он часть манифеста: то, что показано до записи,
   * и есть то, что записывается — планировщик обязан прийти к этим же
   * сторонам, иначе прогон останавливается. */
  sizes: number[];
  /** Where the leftover parts go: `parts - 1` new rungs at the tail of
   * this level's WORD_SEARCH ladder. */
  tailSequences: number[];
  /**
   * Дата, когда запись УЖЕ применена к проду. Такие строки остаются в
   * манифесте навсегда и не удаляются: на них держится
   * `isDensityOwnedRung`, а на нём — защита хвостовых строк от чистки
   * `generate-word-games.ts` (она удаляет всё, что старше расчётного
   * максимума лестницы, а хвост по построению именно там).
   *
   * По умолчанию прогон разгрузки их пропускает: их источники уже в
   * коридоре, и повторная раскладка либо ничего не даст, либо разойдётся
   * с числом частей манифеста.
   */
  applied?: string;
}

/**
 * Worst-first by the severity in density.ts, MEASURED ON PRODUCTION
 * (2026-09-02) — not on dev.db.
 *
 * The previous twenty were measured on the local copy, and the local copy
 * turned out to hold a different bank under the same rung numbers: 1691
 * of 1738 word lists differ, no id is shared, and crosswords differ just
 * as hard (30 of 1262 match). The cause is in the generator, and it is
 * fixed in the same PR as this list — `flashcardCard.findMany` read cards
 * without `orderBy`, so the pool arrived in rowid order, and a seeded
 * shuffle over a differently ordered pool picks different words. See
 * PROGRESS.md 7.83.
 *
 * Production is the reference copy, so this list is what production
 * actually needs. Regenerated by `npm run db:build-density-manifest` run
 * against production; `parts` is what the packer achieved on the real
 * rows, not a number copied from the old file — every one of these twenty
 * splits into exactly 2 grids, where the local list demanded 3 for five
 * of them. Selection rule: src/lib/word-games/rung-class.ts. Nothing was
 * displaced by the placement class this round (0 rungs).
 *
 * Every entry is still a PAID rung. C1/10 looks free at a glance and is
 * not: the free rule is `level !== "C1" && sequence <= 10`, so no C1 rung
 * is ever free, and C1 has no themed-topic row in topics.ts either — its
 * title makes no category promise a split could break. isFreeWordGamePuzzle
 * is untouched and no new URL enters the sitemap.
 */
export const DENSITY_SPLITS: readonly DensitySplit[] = [
  { level: "C1", sequence: 114, parts: 2, sizes: [16, 16], tailSequences: [241], applied: "2026-09-02" },
  { level: "C1", sequence: 68, parts: 2, sizes: [16, 16], tailSequences: [242], applied: "2026-09-02" },
  { level: "B2", sequence: 141, parts: 2, sizes: [16, 16], tailSequences: [328], applied: "2026-09-02" },
  { level: "B2", sequence: 44, parts: 2, sizes: [16, 16], tailSequences: [329], applied: "2026-09-02" },
  { level: "B2", sequence: 163, parts: 2, sizes: [16, 16], tailSequences: [330], applied: "2026-09-02" },
  { level: "C1", sequence: 10, parts: 2, sizes: [16, 16], tailSequences: [243], applied: "2026-09-02" },
  { level: "B2", sequence: 67, parts: 2, sizes: [16, 16], tailSequences: [331], applied: "2026-09-02" },
  { level: "B2", sequence: 113, parts: 2, sizes: [16, 16], tailSequences: [332], applied: "2026-09-02" },
  { level: "C1", sequence: 164, parts: 2, sizes: [16, 16], tailSequences: [244], applied: "2026-09-02" },
  { level: "B2", sequence: 232, parts: 2, sizes: [16, 16], tailSequences: [333], applied: "2026-09-02" },

  // Второй круг. Порядок в файле и есть порядок применения: хвостовые
  // номера первого круга идут раньше, и круг 2, запущенный первым,
  // немедленно объявит дыру в лестнице (сторож ladderGaps, 7.79).
  { level: "B2", sequence: 43, parts: 2, sizes: [16, 16], tailSequences: [334], applied: "2026-09-02" },
  { level: "B2", sequence: 42, parts: 2, sizes: [16, 16], tailSequences: [335], applied: "2026-09-02" },
  { level: "C1", sequence: 138, parts: 2, sizes: [16, 16], tailSequences: [245], applied: "2026-09-02" },
  { level: "C1", sequence: 27, parts: 2, sizes: [16, 16], tailSequences: [246], applied: "2026-09-02" },
  { level: "B1", sequence: 400, parts: 2, sizes: [16, 16], tailSequences: [563], applied: "2026-09-02" },
  { level: "C1", sequence: 24, parts: 2, sizes: [16, 16], tailSequences: [247], applied: "2026-09-02" },
  { level: "C1", sequence: 165, parts: 2, sizes: [16, 16], tailSequences: [248], applied: "2026-09-02" },
  { level: "B2", sequence: 211, parts: 2, sizes: [16, 16], tailSequences: [336], applied: "2026-09-02" },
  { level: "B2", sequence: 65, parts: 2, sizes: [16, 16], tailSequences: [337], applied: "2026-09-02" },
  { level: "C1", sequence: 90, parts: 2, sizes: [16, 16], tailSequences: [249], applied: "2026-09-02" },

  // Сорок рунгов коридора (PROGRESS 7.86), УЖЕ ЗАПИСАННЫЕ В ПРОД 02.09.2026.
  //
  // Почему их здесь не было и почему это была дыра, а не косметика.
  // Заход 7.85/7.86 разошёлся на два PR: код (правило коридора, выбор
  // размера доски, эти сорок записей) и данные (снимок банка «после»).
  // Смёржен был ТОЛЬКО второй. В итоге прод носит 78 строк, которых
  // манифест не описывает, а `maxWordSearchSequence` в
  // prisma/generate-word-games.ts считается как straight + star +
  // densityTailCount(level) — то есть первый же полный прогон генератора
  // удалил бы как «устаревшие» B1 564–571, B2 338–349 и C1 250–267,
  // ровно 38 строк, и слова из них исчезли бы с уровня насовсем. Это та
  // самая ловушка, ради которой densityTailCount вообще написан.
  //
  // Числа взяты не из головы: docs/density-manifest-prod-2026-09-02-round3.json
  // (замер, по которому шла запись), и каждая строка сверена с боевой
  // базой 03.09.2026 — 40 из 40 источников совпали по id и по стороне
  // доски, 38 из 38 хвостов совпали по стороне и по флагам
  // (premiumOnly/curved) со своим источником.
  { level: "C1", sequence: 140, parts: 2, sizes: [14, 18], tailSequences: [250], applied: "2026-09-02" },
  { level: "B2", sequence: 139, parts: 2, sizes: [16, 18], tailSequences: [338], applied: "2026-09-02" },
  { level: "C1", sequence: 69, parts: 2, sizes: [14, 18], tailSequences: [251], applied: "2026-09-02" },
  { level: "C1", sequence: 70, parts: 2, sizes: [14, 18], tailSequences: [252], applied: "2026-09-02" },
  { level: "C1", sequence: 9, parts: 2, sizes: [14, 18], tailSequences: [253], applied: "2026-09-02" },
  { level: "B2", sequence: 17, parts: 2, sizes: [14, 18], tailSequences: [339], applied: "2026-09-02" },
  { level: "B2", sequence: 209, parts: 2, sizes: [14, 18], tailSequences: [340], applied: "2026-09-02" },
  { level: "C1", sequence: 166, parts: 2, sizes: [14, 18], tailSequences: [254], applied: "2026-09-02" },
  { level: "B1", sequence: 67, parts: 2, sizes: [14, 18], tailSequences: [564], applied: "2026-09-02" },
  { level: "B2", sequence: 164, parts: 2, sizes: [16, 16], tailSequences: [341], applied: "2026-09-02" },
  { level: "B2", sequence: 236, parts: 2, sizes: [14, 18], tailSequences: [342], applied: "2026-09-02" },
  { level: "B2", sequence: 41, parts: 2, sizes: [12, 18], tailSequences: [343], applied: "2026-09-02" },
  { level: "C1", sequence: 12, parts: 2, sizes: [14, 18], tailSequences: [255], applied: "2026-09-02" },
  { level: "C1", sequence: 143, parts: 2, sizes: [12, 18], tailSequences: [256], applied: "2026-09-02" },
  { level: "B1", sequence: 259, parts: 2, sizes: [14, 18], tailSequences: [565], applied: "2026-09-02" },
  { level: "B1", sequence: 306, parts: 2, sizes: [14, 18], tailSequences: [566], applied: "2026-09-02" },
  { level: "B2", sequence: 165, parts: 2, sizes: [14, 18], tailSequences: [344], applied: "2026-09-02" },
  { level: "B1", sequence: 188, parts: 2, sizes: [14, 18], tailSequences: [567], applied: "2026-09-02" },
  { level: "B1", sequence: 355, parts: 2, sizes: [14, 18], tailSequences: [568], applied: "2026-09-02" },
  { level: "C1", sequence: 135, parts: 2, sizes: [14, 18], tailSequences: [257], applied: "2026-09-02" },
  { level: "C1", sequence: 118, parts: 2, sizes: [14, 18], tailSequences: [258], applied: "2026-09-02" },
  { level: "C1", sequence: 46, parts: 2, sizes: [14, 18], tailSequences: [259], applied: "2026-09-02" },
  { level: "B2", sequence: 38, parts: 2, sizes: [10, 18], tailSequences: [345], applied: "2026-09-02" },
  { level: "A2", sequence: 162, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-02" },
  { level: "C1", sequence: 116, parts: 2, sizes: [14, 18], tailSequences: [260], applied: "2026-09-02" },
  { level: "B2", sequence: 136, parts: 2, sizes: [14, 18], tailSequences: [346], applied: "2026-09-02" },
  { level: "C1", sequence: 160, parts: 2, sizes: [14, 18], tailSequences: [261], applied: "2026-09-02" },
  { level: "C1", sequence: 93, parts: 2, sizes: [14, 18], tailSequences: [262], applied: "2026-09-02" },
  { level: "C1", sequence: 14, parts: 2, sizes: [10, 18], tailSequences: [263], applied: "2026-09-02" },
  { level: "B2", sequence: 162, parts: 2, sizes: [14, 18], tailSequences: [347], applied: "2026-09-02" },
  { level: "C1", sequence: 162, parts: 2, sizes: [14, 18], tailSequences: [264], applied: "2026-09-02" },
  { level: "B2", sequence: 116, parts: 2, sizes: [14, 18], tailSequences: [348], applied: "2026-09-02" },
  { level: "B2", sequence: 210, parts: 2, sizes: [14, 18], tailSequences: [349], applied: "2026-09-02" },
  { level: "B1", sequence: 282, parts: 2, sizes: [14, 18], tailSequences: [569], applied: "2026-09-02" },
  { level: "B1", sequence: 356, parts: 2, sizes: [12, 18], tailSequences: [570], applied: "2026-09-02" },
  { level: "C1", sequence: 67, parts: 2, sizes: [12, 18], tailSequences: [265], applied: "2026-09-02" },
  { level: "C1", sequence: 40, parts: 2, sizes: [12, 18], tailSequences: [266], applied: "2026-09-02" },
  { level: "B2", sequence: 49, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-02" },
  { level: "B1", sequence: 238, parts: 2, sizes: [12, 18], tailSequences: [571], applied: "2026-09-02" },
  { level: "C1", sequence: 47, parts: 2, sizes: [12, 18], tailSequences: [267], applied: "2026-09-02" },

  // ---- ПОРЦИЯ 1 коридора (PROGRESS 7.101), ЗАПИСАНА В ПРОД 03.09.2026 ----
  //
  // Признак порции: пазл чинится ОДНОЙ сменой размера доски (parts: 1),
  // новая сторона не больше 16, и рунг не входит в те, что видит аноним
  // и Google (isFreeWordGamePuzzle: sequence <= 10 при уровне не C1).
  //
  // Почему именно она первая — числом, а не по вкусу:
  //   · новых строк 0, новых URL 0, доля Premium не двигается вовсе
  //     (31,3% до и после);
  //   · ни одна доска не становится шире 16, а таких банк держит 1396
  //     штук уже сегодня — нового вида игры на телефоне не появляется;
  //   · 115 досок из 124 УМЕНЬШАЮТСЯ (16→14, 16→12, 16→10), 4 растут,
  //     5 остаются той же стороны и перекладываются;
  //   · sitemap.xml и robots.txt после неё обязаны остаться побайтово
  //     теми же файлами — ни один затронутый рунг в sitemap не входит.
  //
  // Медиана занятости порции 39,8% → 56,1%: это НЕ перегруженные пазлы,
  // а разрежённые — доска велика для списка слов, и лечится это именно
  // размером доски, а не добавлением слов (PROGRESS 7.85, обоснование
  // нижней границы коридора 45%).
  //
  // Пересчитывается `npm run report:word-search-portions -- --emit=1`
  // по той базе, против которой запущен.
  //
  // `applied: "2026-09-03"` проставлено 04.09.2026 и не на слово: до этого
  // все 124 записи стояли БЕЗ него, хотя запись на прод уже состоялась.
  // Доказано сравнением локальной копии банка с продовым снимком
  // docs/word-search-baseline-prod-2026-09-04.json: разошлось ровно 124
  // рунга, и множество разошедшихся совпало с этими 124 ПОИМЁННО (ноль
  // лишних в обе стороны). Цена пропуска: прогон разгрузки без --only=
  // берёт именно НЕприменённые записи, то есть заново раскладывал бы 124
  // рунга, которые уже в коридоре.
  { level: "A1", sequence: 11, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 13, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 16, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 18, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 19, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 20, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 21, parts: 1, sizes: [10], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 26, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 31, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 33, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 34, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 37, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 39, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 53, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 54, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 55, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 56, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 57, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 72, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 73, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 74, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 75, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 77, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 78, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 79, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 89, parts: 1, sizes: [16], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 101, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 103, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 104, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 111, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 122, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 124, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 126, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 127, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 128, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 129, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 130, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 131, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A1", sequence: 137, parts: 1, sizes: [16], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 31, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 32, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 33, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 34, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 35, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 36, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 37, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 41, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 53, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 54, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 75, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 78, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 79, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 80, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 81, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 82, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 101, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 103, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 105, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 110, parts: 1, sizes: [16], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 111, parts: 1, sizes: [16], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 119, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 120, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 125, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 126, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 127, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 128, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 149, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 150, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 152, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 155, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 175, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 195, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 196, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 197, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 198, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 199, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 200, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 202, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 204, parts: 1, sizes: [16], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 222, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 223, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 239, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 240, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 246, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 247, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 270, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 271, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 272, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 280, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "A2", sequence: 293, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 50, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 51, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 52, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 53, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 54, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 55, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 56, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 57, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 79, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 102, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 103, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 105, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 126, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 127, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 152, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 221, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 223, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 247, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 270, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 271, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 366, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 367, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 388, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B1", sequence: 389, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "B2", sequence: 31, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B2", sequence: 32, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B2", sequence: 33, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B2", sequence: 103, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B2", sequence: 125, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "B2", sequence: 126, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "C1", sequence: 1, parts: 1, sizes: [10], tailSequences: [], applied: "2026-09-03" },
  { level: "C1", sequence: 2, parts: 1, sizes: [12], tailSequences: [], applied: "2026-09-03" },
  { level: "C1", sequence: 3, parts: 1, sizes: [14], tailSequences: [], applied: "2026-09-03" },
  { level: "C1", sequence: 4, parts: 1, sizes: [16], tailSequences: [], applied: "2026-09-03" },

  // ---- ПИЛОТ ПОРЦИИ 2 коридора (PROGRESS 7.105), ЗАПИСАН В ПРОД 04.09.2026 ----
  //
  // Порция 2 целиком — 421 рунг: пазл чинится ОДНОЙ сменой размера доски
  // (parts: 1), новая сторона 18, рунг вне того, что видит аноним и
  // Google. Здесь только ДВАДЦАТЬ из них: доска впервые уезжает на 18
  // столбцов массово, и это надо посмотреть глазами на телефоне прежде,
  // чем трогать остальные 401.
  //
  // Числа порции 2 перемерены 04.09.2026 заново, а не взяты из манифеста
  // docs/word-search-corridor-portions-prod-2026-09-03.json на веру:
  // планировщик прогнан по всем 421 рунгу и сошёлся с манифестом 421 из
  // 421 по числу частей и по стороне, ноль расхождений, ноль отвергнутых.
  // Новых строк 0, новых URL 0, платных источников 24, в бесплатной
  // десятке 0, доля Premium 31,3% до и после.
  //
  // Правило отбора двадцатки объявлено ДО прогона: три самых тяжёлых по
  // занятости на каждом уровне (это даёт все пять уровней) плюс пять
  // самых тяжёлых по банку из ещё не взятых (это даёт худшие случаи).
  // Вышло: занятость 76,6–83,2% -> 60,8–64,8%, весь топ-10 банка внутри,
  // одиннадцать со словом в 14 букв, то есть с отношением 14/18 = 0,778,
  // у самого края потолка 0,80, где доска шире всего относительно слова.
  //
  // Записано 04.09.2026 двумя кругами по десять, без --force: обновлено на
  // месте 20, новых строк 0. Порог 80%/3 нарушали 15 из 20 до записи и 0
  // из 20 после; все двадцать внутри коридора quality.ts. Семь из них
  // сменили слов на клетку 2 -> 3 при занятости 81% -> 63%, и снимок до
  // пересъёма честно называл это «стало хуже» — порог нарушают >3, а не
  // 3, поэтому по вердикту это переход из «нарушен» в «в норме»
  // (PROGRESS 7.106).
  { level: "A1", sequence: 43, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 114, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 115, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 66, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 94, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 163, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 62, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 181, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 327, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 350, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 378, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 379, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 15, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 35, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 37, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 119, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 181, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 30, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 74, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 170, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },

  // ОСТАТОК ПОРЦИИ 2 — 401 рунг (PROGRESS 7.107). Владелец принял пилот
  // из двадцати по проверке пальцем на живом проде: доска 18×18 читается,
  // все восемнадцать столбцов влезают, рост слов на клетку с 2 до 3
  // глазами не мешает. Отсюда решение, которое НЕ переоткрывается:
  // второй критерий планировщику не задаётся, он по-прежнему целится в
  // занятость, а пересечения сторожит порог 80%/3.
  //
  // Числа перемерены против ЖИВОГО прода 04.09.2026, а не взяты из
  // docs/word-search-corridor-portions-prod-2026-09-03.json на веру: вход
  // сошёлся 401 из 401 по шести полям, планировщик сошёлся с манифестом
  // по стороне и числу частей 401 из 401, отвергнутых 0. Новых строк 0,
  // новых URL 0, в бесплатной десятке 0, доля Premium 31,3% до и после.
  // Досок 18×18 в банке становится 464 (было 63).
  //
  // Побочный эффект предсчитан ДО записи и оказался втрое меньше
  // предсказанного «примерно на трети»: слов на клетку становится 3 у 37
  // рунгов (2 -> 3 у 29, 3 -> 3 у 8), остаётся 2 у 328, падает до 1 у 36,
  // выходит ЗА 3 у НУЛЯ. Порог 80%/3 нарушали 10 из 401 до записи и 0
  // после.
  { level: "A1", sequence: 22, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 24, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 25, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 27, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 29, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 42, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 45, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 64, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 65, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 66, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 67, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 68, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 86, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 88, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 94, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 116, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 117, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 136, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 138, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A1", sequence: 140, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 15, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 16, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 17, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 19, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 20, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 22, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 24, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 43, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 44, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 45, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 50, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 60, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 61, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 62, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 63, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 64, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 69, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 70, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 84, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 85, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 86, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 87, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 88, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 93, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 95, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 108, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 109, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 112, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 113, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 114, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 115, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 124, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 132, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 133, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 134, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 135, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 136, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 141, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 142, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 143, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 146, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 164, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 165, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 169, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 170, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 179, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 180, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 181, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 182, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 184, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 185, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 188, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 189, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 191, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 206, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 207, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 208, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 210, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 213, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 214, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 215, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 216, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 217, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 228, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 232, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 233, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 234, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 235, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 242, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 252, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 253, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 254, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 255, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 256, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 258, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 260, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 261, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 262, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 263, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 282, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 283, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 284, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 285, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 290, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 297, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "A2", sequence: 299, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 11, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 13, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 15, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 16, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 18, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 23, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 25, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 28, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 30, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 32, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 35, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 38, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 39, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 40, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 41, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 42, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 43, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 44, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 45, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 59, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 60, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 73, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 74, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 75, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 82, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 83, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 84, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 85, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 88, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 93, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 94, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 95, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 96, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 97, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 120, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 122, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 131, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 132, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 133, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 141, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 144, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 145, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 147, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 158, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 159, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 160, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 161, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 162, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 163, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 164, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 166, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 167, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 168, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 169, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 170, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 172, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 179, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 180, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 182, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 191, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 192, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 193, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 194, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 195, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 196, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 202, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 203, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 204, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 205, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 206, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 207, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 208, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 209, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 213, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 214, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 215, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 216, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 226, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 227, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 228, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 229, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 230, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 239, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 241, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 242, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 251, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 252, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 253, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 254, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 255, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 263, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 265, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 276, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 279, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 289, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 290, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 292, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 298, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 299, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 300, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 301, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 310, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 311, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 312, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 313, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 316, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 325, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 326, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 328, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 329, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 330, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 331, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 332, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 333, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 334, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 335, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 336, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 338, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 339, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 340, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 345, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 346, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 347, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 348, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 349, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 351, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 360, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 361, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 362, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 363, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 364, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 365, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 374, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 375, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 380, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 381, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 382, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 395, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 396, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B1", sequence: 397, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 11, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 13, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 16, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 18, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 20, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 23, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 25, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 26, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 27, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 29, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 34, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 50, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 51, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 52, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 53, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 54, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 55, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 56, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 57, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 59, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 61, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 64, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 74, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 75, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 76, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 77, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 80, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 81, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 82, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 83, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 84, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 92, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 93, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 97, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 98, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 99, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 100, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 102, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 104, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 105, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 106, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 107, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 108, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 120, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 121, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 123, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 128, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 129, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 130, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 131, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 145, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 146, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 147, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 153, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 154, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 155, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 157, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 158, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 170, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 171, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 172, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 173, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 174, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 175, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 176, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 177, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 178, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 179, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 180, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 182, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 183, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 185, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 186, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 191, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 193, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 194, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 195, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 196, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 200, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 201, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 202, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 203, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 204, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 214, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 215, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 216, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 219, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 220, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 222, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 224, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 225, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 226, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 227, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 228, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "B2", sequence: 229, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 5, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 6, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 16, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 18, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 20, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 22, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 26, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 31, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 32, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 33, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 34, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 52, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 53, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 54, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 55, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 56, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 57, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 58, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 59, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 76, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 77, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 78, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 79, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 80, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 81, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 82, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 83, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 96, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 100, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 101, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 102, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 103, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 104, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 105, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 106, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 107, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 108, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 110, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 111, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 124, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 125, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 126, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 127, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 129, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 130, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 131, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 133, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 134, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 147, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 148, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 149, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 153, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 154, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 155, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 156, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 157, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 171, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 172, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 173, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },
  { level: "C1", sequence: 174, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-04" },

  // ---- ПОРЦИЯ 3 коридора (PROGRESS 7.108), ЗАПИСАНА В ПРОД 04.09.2026 ----
  //
  // Признак порции: одной сменой размера доски пазл уже не чинится —
  // слова делятся на ДВЕ сетки (parts: 2), и это первые записи коридора,
  // после которых в банке появляются НОВЫЕ СТРОКИ и новые URL. Потолок
  // стороны при этом 16: нового вида доски на телефоне не возникает, то
  // есть цена (строки, URL, доля Premium) и риск (18 столбцов) здесь
  // разведены намеренно.
  //
  // Числа перемерены против ЖИВОГО прода 04.09.2026, а не взяты из
  // docs/word-search-corridor-portions-prod-2026-09-03.json на веру: вход
  // сошёлся 34 из 34 по шести полям (id, слова поэлементно и по порядку,
  // сторона доски, занятость, premiumOnly, curved), планировщик сошёлся с
  // манифестом по сторонам и числу частей 34 из 34, отвергнутых 0.
  // Новых строк 34, новых URL 68, платных источников 2, в бесплатной
  // десятке 0, в живом sitemap 0.
  //
  // Занятость источников: медиана 81,8% -> 49,6%, край 69,1–89,8% ->
  // 45,4–62,8%. Порог 80%/3 нарушали 28 из 34 до записи и 0 из 34 после.
  // Слов на клетку у строки-источника не выросло НИ У ОДНОГО рунга
  // порции: упало у 10, осталось прежним у 24.

  { level: "A1", sequence: 41, parts: 2, sizes: [10, 16], tailSequences: [197], applied: "2026-09-04" },
  { level: "A1", sequence: 139, parts: 2, sizes: [14, 16], tailSequences: [198], applied: "2026-09-04" },
  { level: "A2", sequence: 67, parts: 2, sizes: [14, 16], tailSequences: [414], applied: "2026-09-04" },
  { level: "A2", sequence: 144, parts: 2, sizes: [14, 14], tailSequences: [415], applied: "2026-09-04" },
  { level: "A2", sequence: 186, parts: 2, sizes: [12, 16], tailSequences: [416], applied: "2026-09-04" },
  { level: "A2", sequence: 212, parts: 2, sizes: [14, 16], tailSequences: [417], applied: "2026-09-04" },
  { level: "B1", sequence: 19, parts: 2, sizes: [14, 16], tailSequences: [572], applied: "2026-09-04" },
  { level: "B1", sequence: 24, parts: 2, sizes: [14, 16], tailSequences: [573], applied: "2026-09-04" },
  { level: "B1", sequence: 86, parts: 2, sizes: [14, 16], tailSequences: [574], applied: "2026-09-04" },
  { level: "B1", sequence: 90, parts: 2, sizes: [14, 16], tailSequences: [575], applied: "2026-09-04" },
  { level: "B1", sequence: 136, parts: 2, sizes: [14, 16], tailSequences: [576], applied: "2026-09-04" },
  { level: "B1", sequence: 137, parts: 2, sizes: [14, 16], tailSequences: [577], applied: "2026-09-04" },
  { level: "B1", sequence: 138, parts: 2, sizes: [14, 14], tailSequences: [578], applied: "2026-09-04" },
  { level: "B1", sequence: 143, parts: 2, sizes: [14, 16], tailSequences: [579], applied: "2026-09-04" },
  { level: "B1", sequence: 184, parts: 2, sizes: [14, 16], tailSequences: [580], applied: "2026-09-04" },
  { level: "B1", sequence: 210, parts: 2, sizes: [14, 14], tailSequences: [581], applied: "2026-09-04" },
  { level: "B1", sequence: 211, parts: 2, sizes: [14, 16], tailSequences: [582], applied: "2026-09-04" },
  { level: "B1", sequence: 212, parts: 2, sizes: [12, 16], tailSequences: [583], applied: "2026-09-04" },
  { level: "B1", sequence: 280, parts: 2, sizes: [14, 16], tailSequences: [584], applied: "2026-09-04" },
  { level: "B1", sequence: 283, parts: 2, sizes: [14, 14], tailSequences: [585], applied: "2026-09-04" },
  { level: "B1", sequence: 284, parts: 2, sizes: [14, 16], tailSequences: [586], applied: "2026-09-04" },
  { level: "B1", sequence: 286, parts: 2, sizes: [12, 16], tailSequences: [587], applied: "2026-09-04" },
  { level: "B1", sequence: 307, parts: 2, sizes: [14, 16], tailSequences: [588], applied: "2026-09-04" },
  { level: "B1", sequence: 308, parts: 2, sizes: [14, 16], tailSequences: [589], applied: "2026-09-04" },
  { level: "B1", sequence: 353, parts: 2, sizes: [14, 16], tailSequences: [590], applied: "2026-09-04" },
  { level: "B1", sequence: 376, parts: 2, sizes: [14, 16], tailSequences: [591], applied: "2026-09-04" },
  { level: "B1", sequence: 377, parts: 2, sizes: [14, 16], tailSequences: [592], applied: "2026-09-04" },
  { level: "B1", sequence: 406, parts: 2, sizes: [14, 16], tailSequences: [593], applied: "2026-09-04" },
  { level: "B2", sequence: 24, parts: 2, sizes: [14, 14], tailSequences: [350], applied: "2026-09-04" },
  { level: "B2", sequence: 89, parts: 2, sizes: [16, 16], tailSequences: [351], applied: "2026-09-04" },
  { level: "B2", sequence: 91, parts: 2, sizes: [14, 14], tailSequences: [352], applied: "2026-09-04" },
  { level: "C1", sequence: 17, parts: 2, sizes: [16, 16], tailSequences: [268], applied: "2026-09-04" },
  { level: "C1", sequence: 44, parts: 2, sizes: [14, 14], tailSequences: [269], applied: "2026-09-04" },
  { level: "C1", sequence: 66, parts: 2, sizes: [14, 14], tailSequences: [270], applied: "2026-09-04" },

  // ---- ПОРЦИЯ 4 коридора (PROGRESS 7.108), ЗАПИСАНА В ПРОД 04.09.2026 ----
  //
  // Самая дорогая порция: деление на две сетки И вторая часть на доске
  // 18×18. Отсюда почти все новые строки банка и всё падение доли
  // Premium — знаменатель растёт на 182 строки, а платных среди
  // источников 15.
  //
  // Числа перемерены против живого прода 04.09.2026 тем же способом:
  // вход сошёлся 182 из 182 по шести полям, планировщик сошёлся с
  // манифестом по сторонам и числу частей 182 из 182, отвергнутых 0.
  // Новых строк 182, новых URL 364, в бесплатной десятке 0, в живом
  // sitemap 0. Досок 18×18 в банке становится 643: хвосты дают +182, а
  // три источника, лежавшие на 18, уезжают на 16, то есть чистая
  // прибавка 179.
  //
  // Занятость источников: медиана 86,1% -> 48,2%, край 77,7–94,5% ->
  // 45,0–58,3%. Порог 80%/3 нарушали 169 из 182 до записи (тяжёлых 34) и
  // 0 из 182 после. Слов на клетку у строки-источника выросло 2 -> 3 у
  // 14 рунгов, упало у 68, осталось прежним у 100; ЗА 3 не вышел ни
  // один — ни у источника, ни у хвоста.

  { level: "A2", sequence: 12, parts: 2, sizes: [12, 18], tailSequences: [418], applied: "2026-09-04" },
  { level: "A2", sequence: 14, parts: 2, sizes: [10, 18], tailSequences: [419], applied: "2026-09-04" },
  { level: "A2", sequence: 42, parts: 2, sizes: [10, 18], tailSequences: [420], applied: "2026-09-04" },
  { level: "A2", sequence: 65, parts: 2, sizes: [10, 18], tailSequences: [421], applied: "2026-09-04" },
  { level: "A2", sequence: 68, parts: 2, sizes: [12, 18], tailSequences: [422], applied: "2026-09-04" },
  { level: "A2", sequence: 89, parts: 2, sizes: [12, 18], tailSequences: [423], applied: "2026-09-04" },
  { level: "A2", sequence: 90, parts: 2, sizes: [12, 18], tailSequences: [424], applied: "2026-09-04" },
  { level: "A2", sequence: 91, parts: 2, sizes: [12, 18], tailSequences: [425], applied: "2026-09-04" },
  { level: "A2", sequence: 92, parts: 2, sizes: [10, 18], tailSequences: [426], applied: "2026-09-04" },
  { level: "A2", sequence: 137, parts: 2, sizes: [10, 18], tailSequences: [427], applied: "2026-09-04" },
  { level: "A2", sequence: 138, parts: 2, sizes: [12, 18], tailSequences: [428], applied: "2026-09-04" },
  { level: "A2", sequence: 139, parts: 2, sizes: [12, 18], tailSequences: [429], applied: "2026-09-04" },
  { level: "A2", sequence: 140, parts: 2, sizes: [10, 18], tailSequences: [430], applied: "2026-09-04" },
  { level: "A2", sequence: 183, parts: 2, sizes: [10, 18], tailSequences: [431], applied: "2026-09-04" },
  { level: "A2", sequence: 187, parts: 2, sizes: [12, 18], tailSequences: [432], applied: "2026-09-04" },
  { level: "A2", sequence: 209, parts: 2, sizes: [10, 18], tailSequences: [433], applied: "2026-09-04" },
  { level: "A2", sequence: 211, parts: 2, sizes: [12, 18], tailSequences: [434], applied: "2026-09-04" },
  { level: "A2", sequence: 257, parts: 2, sizes: [10, 18], tailSequences: [435], applied: "2026-09-04" },
  { level: "A2", sequence: 259, parts: 2, sizes: [12, 18], tailSequences: [436], applied: "2026-09-04" },
  { level: "B1", sequence: 12, parts: 2, sizes: [14, 18], tailSequences: [594], applied: "2026-09-04" },
  { level: "B1", sequence: 17, parts: 2, sizes: [12, 18], tailSequences: [595], applied: "2026-09-04" },
  { level: "B1", sequence: 27, parts: 2, sizes: [10, 18], tailSequences: [596], applied: "2026-09-04" },
  { level: "B1", sequence: 29, parts: 2, sizes: [12, 18], tailSequences: [597], applied: "2026-09-04" },
  { level: "B1", sequence: 61, parts: 2, sizes: [10, 18], tailSequences: [598], applied: "2026-09-04" },
  { level: "B1", sequence: 63, parts: 2, sizes: [12, 18], tailSequences: [599], applied: "2026-09-04" },
  { level: "B1", sequence: 64, parts: 2, sizes: [12, 18], tailSequences: [600], applied: "2026-09-04" },
  { level: "B1", sequence: 65, parts: 2, sizes: [12, 18], tailSequences: [601], applied: "2026-09-04" },
  { level: "B1", sequence: 66, parts: 2, sizes: [12, 18], tailSequences: [602], applied: "2026-09-04" },
  { level: "B1", sequence: 68, parts: 2, sizes: [14, 18], tailSequences: [603], applied: "2026-09-04" },
  { level: "B1", sequence: 69, parts: 2, sizes: [12, 18], tailSequences: [604], applied: "2026-09-04" },
  { level: "B1", sequence: 70, parts: 2, sizes: [12, 18], tailSequences: [605], applied: "2026-09-04" },
  { level: "B1", sequence: 71, parts: 2, sizes: [10, 18], tailSequences: [606], applied: "2026-09-04" },
  { level: "B1", sequence: 72, parts: 2, sizes: [12, 18], tailSequences: [607], applied: "2026-09-04" },
  { level: "B1", sequence: 87, parts: 2, sizes: [10, 18], tailSequences: [608], applied: "2026-09-04" },
  { level: "B1", sequence: 89, parts: 2, sizes: [12, 18], tailSequences: [609], applied: "2026-09-04" },
  { level: "B1", sequence: 91, parts: 2, sizes: [10, 18], tailSequences: [610], applied: "2026-09-04" },
  { level: "B1", sequence: 92, parts: 2, sizes: [14, 18], tailSequences: [611], applied: "2026-09-04" },
  { level: "B1", sequence: 112, parts: 2, sizes: [12, 18], tailSequences: [612], applied: "2026-09-04" },
  { level: "B1", sequence: 113, parts: 2, sizes: [12, 18], tailSequences: [613], applied: "2026-09-04" },
  { level: "B1", sequence: 114, parts: 2, sizes: [12, 18], tailSequences: [614], applied: "2026-09-04" },
  { level: "B1", sequence: 115, parts: 2, sizes: [14, 18], tailSequences: [615], applied: "2026-09-04" },
  { level: "B1", sequence: 116, parts: 2, sizes: [12, 18], tailSequences: [616], applied: "2026-09-04" },
  { level: "B1", sequence: 117, parts: 2, sizes: [12, 18], tailSequences: [617], applied: "2026-09-04" },
  { level: "B1", sequence: 118, parts: 2, sizes: [12, 18], tailSequences: [618], applied: "2026-09-04" },
  { level: "B1", sequence: 119, parts: 2, sizes: [12, 18], tailSequences: [619], applied: "2026-09-04" },
  { level: "B1", sequence: 121, parts: 2, sizes: [10, 18], tailSequences: [620], applied: "2026-09-04" },
  { level: "B1", sequence: 134, parts: 2, sizes: [12, 18], tailSequences: [621], applied: "2026-09-04" },
  { level: "B1", sequence: 135, parts: 2, sizes: [12, 18], tailSequences: [622], applied: "2026-09-04" },
  { level: "B1", sequence: 139, parts: 2, sizes: [14, 18], tailSequences: [623], applied: "2026-09-04" },
  { level: "B1", sequence: 140, parts: 2, sizes: [12, 18], tailSequences: [624], applied: "2026-09-04" },
  { level: "B1", sequence: 142, parts: 2, sizes: [12, 18], tailSequences: [625], applied: "2026-09-04" },
  { level: "B1", sequence: 183, parts: 2, sizes: [10, 18], tailSequences: [626], applied: "2026-09-04" },
  { level: "B1", sequence: 185, parts: 2, sizes: [12, 18], tailSequences: [627], applied: "2026-09-04" },
  { level: "B1", sequence: 186, parts: 2, sizes: [12, 18], tailSequences: [628], applied: "2026-09-04" },
  { level: "B1", sequence: 187, parts: 2, sizes: [12, 18], tailSequences: [629], applied: "2026-09-04" },
  { level: "B1", sequence: 189, parts: 2, sizes: [14, 18], tailSequences: [630], applied: "2026-09-04" },
  { level: "B1", sequence: 190, parts: 2, sizes: [12, 18], tailSequences: [631], applied: "2026-09-04" },
  { level: "B1", sequence: 231, parts: 2, sizes: [12, 18], tailSequences: [632], applied: "2026-09-04" },
  { level: "B1", sequence: 232, parts: 2, sizes: [12, 18], tailSequences: [633], applied: "2026-09-04" },
  { level: "B1", sequence: 233, parts: 2, sizes: [12, 18], tailSequences: [634], applied: "2026-09-04" },
  { level: "B1", sequence: 234, parts: 2, sizes: [14, 18], tailSequences: [635], applied: "2026-09-04" },
  { level: "B1", sequence: 235, parts: 2, sizes: [14, 18], tailSequences: [636], applied: "2026-09-04" },
  { level: "B1", sequence: 236, parts: 2, sizes: [12, 18], tailSequences: [637], applied: "2026-09-04" },
  { level: "B1", sequence: 237, parts: 2, sizes: [12, 18], tailSequences: [638], applied: "2026-09-04" },
  { level: "B1", sequence: 240, parts: 2, sizes: [12, 18], tailSequences: [639], applied: "2026-09-04" },
  { level: "B1", sequence: 256, parts: 2, sizes: [12, 18], tailSequences: [640], applied: "2026-09-04" },
  { level: "B1", sequence: 257, parts: 2, sizes: [12, 18], tailSequences: [641], applied: "2026-09-04" },
  { level: "B1", sequence: 258, parts: 2, sizes: [12, 18], tailSequences: [642], applied: "2026-09-04" },
  { level: "B1", sequence: 260, parts: 2, sizes: [12, 18], tailSequences: [643], applied: "2026-09-04" },
  { level: "B1", sequence: 261, parts: 2, sizes: [12, 18], tailSequences: [644], applied: "2026-09-04" },
  { level: "B1", sequence: 262, parts: 2, sizes: [10, 18], tailSequences: [645], applied: "2026-09-04" },
  { level: "B1", sequence: 281, parts: 2, sizes: [12, 18], tailSequences: [646], applied: "2026-09-04" },
  { level: "B1", sequence: 285, parts: 2, sizes: [14, 18], tailSequences: [647], applied: "2026-09-04" },
  { level: "B1", sequence: 287, parts: 2, sizes: [12, 18], tailSequences: [648], applied: "2026-09-04" },
  { level: "B1", sequence: 288, parts: 2, sizes: [12, 18], tailSequences: [649], applied: "2026-09-04" },
  { level: "B1", sequence: 302, parts: 2, sizes: [12, 18], tailSequences: [650], applied: "2026-09-04" },
  { level: "B1", sequence: 303, parts: 2, sizes: [12, 18], tailSequences: [651], applied: "2026-09-04" },
  { level: "B1", sequence: 304, parts: 2, sizes: [10, 18], tailSequences: [652], applied: "2026-09-04" },
  { level: "B1", sequence: 305, parts: 2, sizes: [12, 18], tailSequences: [653], applied: "2026-09-04" },
  { level: "B1", sequence: 309, parts: 2, sizes: [10, 18], tailSequences: [654], applied: "2026-09-04" },
  { level: "B1", sequence: 352, parts: 2, sizes: [12, 18], tailSequences: [655], applied: "2026-09-04" },
  { level: "B1", sequence: 354, parts: 2, sizes: [14, 18], tailSequences: [656], applied: "2026-09-04" },
  { level: "B1", sequence: 357, parts: 2, sizes: [14, 18], tailSequences: [657], applied: "2026-09-04" },
  { level: "B1", sequence: 358, parts: 2, sizes: [12, 18], tailSequences: [658], applied: "2026-09-04" },
  { level: "B1", sequence: 359, parts: 2, sizes: [12, 18], tailSequences: [659], applied: "2026-09-04" },
  { level: "B1", sequence: 398, parts: 2, sizes: [10, 18], tailSequences: [660], applied: "2026-09-04" },
  { level: "B1", sequence: 399, parts: 2, sizes: [12, 18], tailSequences: [661], applied: "2026-09-04" },
  { level: "B1", sequence: 401, parts: 2, sizes: [12, 18], tailSequences: [662], applied: "2026-09-04" },
  { level: "B1", sequence: 402, parts: 2, sizes: [12, 18], tailSequences: [663], applied: "2026-09-04" },
  { level: "B1", sequence: 403, parts: 2, sizes: [14, 18], tailSequences: [664], applied: "2026-09-04" },
  { level: "B1", sequence: 404, parts: 2, sizes: [14, 18], tailSequences: [665], applied: "2026-09-04" },
  { level: "B1", sequence: 405, parts: 2, sizes: [12, 18], tailSequences: [666], applied: "2026-09-04" },
  { level: "B1", sequence: 407, parts: 2, sizes: [12, 18], tailSequences: [667], applied: "2026-09-04" },
  { level: "B2", sequence: 12, parts: 2, sizes: [12, 18], tailSequences: [353], applied: "2026-09-04" },
  { level: "B2", sequence: 14, parts: 2, sizes: [14, 18], tailSequences: [354], applied: "2026-09-04" },
  { level: "B2", sequence: 19, parts: 2, sizes: [12, 18], tailSequences: [355], applied: "2026-09-04" },
  { level: "B2", sequence: 39, parts: 2, sizes: [10, 18], tailSequences: [356], applied: "2026-09-04" },
  { level: "B2", sequence: 45, parts: 2, sizes: [14, 18], tailSequences: [357], applied: "2026-09-04" },
  { level: "B2", sequence: 46, parts: 2, sizes: [14, 18], tailSequences: [358], applied: "2026-09-04" },
  { level: "B2", sequence: 47, parts: 2, sizes: [10, 18], tailSequences: [359], applied: "2026-09-04" },
  { level: "B2", sequence: 66, parts: 2, sizes: [14, 18], tailSequences: [360], applied: "2026-09-04" },
  { level: "B2", sequence: 68, parts: 2, sizes: [14, 18], tailSequences: [361], applied: "2026-09-04" },
  { level: "B2", sequence: 69, parts: 2, sizes: [14, 18], tailSequences: [362], applied: "2026-09-04" },
  { level: "B2", sequence: 70, parts: 2, sizes: [14, 18], tailSequences: [363], applied: "2026-09-04" },
  { level: "B2", sequence: 71, parts: 2, sizes: [12, 18], tailSequences: [364], applied: "2026-09-04" },
  { level: "B2", sequence: 72, parts: 2, sizes: [10, 18], tailSequences: [365], applied: "2026-09-04" },
  { level: "B2", sequence: 86, parts: 2, sizes: [12, 18], tailSequences: [366], applied: "2026-09-04" },
  { level: "B2", sequence: 87, parts: 2, sizes: [12, 18], tailSequences: [367], applied: "2026-09-04" },
  { level: "B2", sequence: 88, parts: 2, sizes: [12, 18], tailSequences: [368], applied: "2026-09-04" },
  { level: "B2", sequence: 90, parts: 2, sizes: [12, 18], tailSequences: [369], applied: "2026-09-04" },
  { level: "B2", sequence: 94, parts: 2, sizes: [12, 18], tailSequences: [370], applied: "2026-09-04" },
  { level: "B2", sequence: 95, parts: 2, sizes: [12, 18], tailSequences: [371], applied: "2026-09-04" },
  { level: "B2", sequence: 96, parts: 2, sizes: [12, 18], tailSequences: [372], applied: "2026-09-04" },
  { level: "B2", sequence: 111, parts: 2, sizes: [14, 18], tailSequences: [373], applied: "2026-09-04" },
  { level: "B2", sequence: 112, parts: 2, sizes: [14, 18], tailSequences: [374], applied: "2026-09-04" },
  { level: "B2", sequence: 114, parts: 2, sizes: [14, 18], tailSequences: [375], applied: "2026-09-04" },
  { level: "B2", sequence: 115, parts: 2, sizes: [14, 18], tailSequences: [376], applied: "2026-09-04" },
  { level: "B2", sequence: 117, parts: 2, sizes: [12, 18], tailSequences: [377], applied: "2026-09-04" },
  { level: "B2", sequence: 118, parts: 2, sizes: [12, 18], tailSequences: [378], applied: "2026-09-04" },
  { level: "B2", sequence: 135, parts: 2, sizes: [12, 18], tailSequences: [379], applied: "2026-09-04" },
  { level: "B2", sequence: 137, parts: 2, sizes: [14, 18], tailSequences: [380], applied: "2026-09-04" },
  { level: "B2", sequence: 138, parts: 2, sizes: [14, 18], tailSequences: [381], applied: "2026-09-04" },
  { level: "B2", sequence: 140, parts: 2, sizes: [14, 18], tailSequences: [382], applied: "2026-09-04" },
  { level: "B2", sequence: 142, parts: 2, sizes: [12, 18], tailSequences: [383], applied: "2026-09-04" },
  { level: "B2", sequence: 159, parts: 2, sizes: [12, 18], tailSequences: [384], applied: "2026-09-04" },
  { level: "B2", sequence: 160, parts: 2, sizes: [12, 18], tailSequences: [385], applied: "2026-09-04" },
  { level: "B2", sequence: 161, parts: 2, sizes: [14, 18], tailSequences: [386], applied: "2026-09-04" },
  { level: "B2", sequence: 166, parts: 2, sizes: [10, 18], tailSequences: [387], applied: "2026-09-04" },
  { level: "B2", sequence: 167, parts: 2, sizes: [14, 18], tailSequences: [388], applied: "2026-09-04" },
  { level: "B2", sequence: 184, parts: 2, sizes: [12, 18], tailSequences: [389], applied: "2026-09-04" },
  { level: "B2", sequence: 187, parts: 2, sizes: [12, 18], tailSequences: [390], applied: "2026-09-04" },
  { level: "B2", sequence: 188, parts: 2, sizes: [12, 18], tailSequences: [391], applied: "2026-09-04" },
  { level: "B2", sequence: 189, parts: 2, sizes: [12, 18], tailSequences: [392], applied: "2026-09-04" },
  { level: "B2", sequence: 190, parts: 2, sizes: [12, 18], tailSequences: [393], applied: "2026-09-04" },
  { level: "B2", sequence: 192, parts: 2, sizes: [12, 18], tailSequences: [394], applied: "2026-09-04" },
  { level: "B2", sequence: 206, parts: 2, sizes: [10, 18], tailSequences: [395], applied: "2026-09-04" },
  { level: "B2", sequence: 207, parts: 2, sizes: [12, 18], tailSequences: [396], applied: "2026-09-04" },
  { level: "B2", sequence: 208, parts: 2, sizes: [14, 18], tailSequences: [397], applied: "2026-09-04" },
  { level: "B2", sequence: 212, parts: 2, sizes: [14, 18], tailSequences: [398], applied: "2026-09-04" },
  { level: "B2", sequence: 213, parts: 2, sizes: [12, 18], tailSequences: [399], applied: "2026-09-04" },
  { level: "B2", sequence: 231, parts: 2, sizes: [10, 18], tailSequences: [400], applied: "2026-09-04" },
  { level: "B2", sequence: 233, parts: 2, sizes: [14, 18], tailSequences: [401], applied: "2026-09-04" },
  { level: "B2", sequence: 234, parts: 2, sizes: [12, 18], tailSequences: [402], applied: "2026-09-04" },
  { level: "B2", sequence: 235, parts: 2, sizes: [14, 18], tailSequences: [403], applied: "2026-09-04" },
  { level: "B2", sequence: 237, parts: 2, sizes: [14, 18], tailSequences: [404], applied: "2026-09-04" },
  { level: "C1", sequence: 29, parts: 2, sizes: [14, 18], tailSequences: [271], applied: "2026-09-04" },
  { level: "C1", sequence: 39, parts: 2, sizes: [10, 18], tailSequences: [272], applied: "2026-09-04" },
  { level: "C1", sequence: 41, parts: 2, sizes: [12, 18], tailSequences: [273], applied: "2026-09-04" },
  { level: "C1", sequence: 42, parts: 2, sizes: [12, 18], tailSequences: [274], applied: "2026-09-04" },
  { level: "C1", sequence: 43, parts: 2, sizes: [12, 18], tailSequences: [275], applied: "2026-09-04" },
  { level: "C1", sequence: 45, parts: 2, sizes: [12, 18], tailSequences: [276], applied: "2026-09-04" },
  { level: "C1", sequence: 63, parts: 2, sizes: [10, 18], tailSequences: [277], applied: "2026-09-04" },
  { level: "C1", sequence: 64, parts: 2, sizes: [12, 18], tailSequences: [278], applied: "2026-09-04" },
  { level: "C1", sequence: 65, parts: 2, sizes: [12, 18], tailSequences: [279], applied: "2026-09-04" },
  { level: "C1", sequence: 71, parts: 2, sizes: [14, 18], tailSequences: [280], applied: "2026-09-04" },
  { level: "C1", sequence: 72, parts: 2, sizes: [12, 18], tailSequences: [281], applied: "2026-09-04" },
  { level: "C1", sequence: 73, parts: 2, sizes: [12, 18], tailSequences: [282], applied: "2026-09-04" },
  { level: "C1", sequence: 86, parts: 2, sizes: [10, 18], tailSequences: [283], applied: "2026-09-04" },
  { level: "C1", sequence: 87, parts: 2, sizes: [12, 18], tailSequences: [284], applied: "2026-09-04" },
  { level: "C1", sequence: 88, parts: 2, sizes: [12, 18], tailSequences: [285], applied: "2026-09-04" },
  { level: "C1", sequence: 89, parts: 2, sizes: [12, 18], tailSequences: [286], applied: "2026-09-04" },
  { level: "C1", sequence: 91, parts: 2, sizes: [16, 18], tailSequences: [287], applied: "2026-09-04" },
  { level: "C1", sequence: 92, parts: 2, sizes: [14, 18], tailSequences: [288], applied: "2026-09-04" },
  { level: "C1", sequence: 94, parts: 2, sizes: [14, 18], tailSequences: [289], applied: "2026-09-04" },
  { level: "C1", sequence: 95, parts: 2, sizes: [14, 18], tailSequences: [290], applied: "2026-09-04" },
  { level: "C1", sequence: 97, parts: 2, sizes: [10, 18], tailSequences: [291], applied: "2026-09-04" },
  { level: "C1", sequence: 109, parts: 2, sizes: [10, 18], tailSequences: [292], applied: "2026-09-04" },
  { level: "C1", sequence: 112, parts: 2, sizes: [12, 18], tailSequences: [293], applied: "2026-09-04" },
  { level: "C1", sequence: 113, parts: 2, sizes: [14, 18], tailSequences: [294], applied: "2026-09-04" },
  { level: "C1", sequence: 115, parts: 2, sizes: [16, 18], tailSequences: [295], applied: "2026-09-04" },
  { level: "C1", sequence: 117, parts: 2, sizes: [14, 18], tailSequences: [296], applied: "2026-09-04" },
  { level: "C1", sequence: 132, parts: 2, sizes: [12, 18], tailSequences: [297], applied: "2026-09-04" },
  { level: "C1", sequence: 136, parts: 2, sizes: [14, 18], tailSequences: [298], applied: "2026-09-04" },
  { level: "C1", sequence: 137, parts: 2, sizes: [14, 18], tailSequences: [299], applied: "2026-09-04" },
  { level: "C1", sequence: 139, parts: 2, sizes: [16, 18], tailSequences: [300], applied: "2026-09-04" },
  { level: "C1", sequence: 141, parts: 2, sizes: [16, 18], tailSequences: [301], applied: "2026-09-04" },
  { level: "C1", sequence: 142, parts: 2, sizes: [14, 18], tailSequences: [302], applied: "2026-09-04" },
  { level: "C1", sequence: 159, parts: 2, sizes: [14, 18], tailSequences: [303], applied: "2026-09-04" },
  { level: "C1", sequence: 161, parts: 2, sizes: [14, 18], tailSequences: [304], applied: "2026-09-04" },
  { level: "C1", sequence: 163, parts: 2, sizes: [16, 18], tailSequences: [305], applied: "2026-09-04" },
  { level: "C1", sequence: 167, parts: 2, sizes: [14, 18], tailSequences: [306], applied: "2026-09-04" },
  { level: "C1", sequence: 168, parts: 2, sizes: [10, 18], tailSequences: [307], applied: "2026-09-04" },
];

/** How many sequences each level's WORD_SEARCH ladder gains beyond what
 * generate-word-games.ts itself writes. */
export function densityTailCount(level: string): number {
  return DENSITY_SPLITS.filter((s) => s.level === level).reduce((n, s) => n + s.tailSequences.length, 0);
}

/** True for a rung the redistribution owns — either a split source or one
 * of its tail rungs. generate-word-games.ts leaves both alone. */
export function isDensityOwnedRung(type: string, level: string, sequence: number): boolean {
  if (type !== "WORD_SEARCH") return false;
  return DENSITY_SPLITS.some(
    (s) => s.level === level && (s.sequence === sequence || s.tailSequences.includes(sequence)),
  );
}

export function findDensitySplit(level: string, sequence: number): DensitySplit | undefined {
  return DENSITY_SPLITS.find((s) => s.level === level && s.sequence === sequence);
}

/** Every tail sequence the manifest will create on one level, ascending. */
export function densityTails(level: string): number[] {
  return DENSITY_SPLITS.filter((s) => s.level === level)
    .flatMap((s) => s.tailSequences)
    .sort((a, b) => a - b);
}

/** Levels the manifest touches at all. */
export function densityLevels(): string[] {
  return [...new Set(DENSITY_SPLITS.map((s) => s.level))].sort();
}

/**
 * Why a gap in the ladder is a defect and not a cosmetic complaint.
 *
 * WordGamesPicker renders `Array.from({length: total}, (_, i) => i + 1)` —
 * it asks the database how MANY rows a (type, level) pair has and then
 * links sequences 1…count. It never asks WHICH sequences exist. So a
 * ladder of 333 rows numbered 1…332 plus 340 renders links 1…333: the
 * row at 340 is unreachable, and 333 is a link to a 404. Both halves of
 * that are silent — nothing throws, nothing logs.
 *
 * Every level's WORD_SEARCH ladder is contiguous 1…N today (verified over
 * all 1738 rows of the 2026-09-01 baseline), and the redistribution is
 * the first thing that ever appends rows by hand, so it is the first
 * thing that can break it. Hence this: given the sequences a level
 * already has plus the ones the manifest would add, the union must still
 * be exactly 1…N.
 */
export function ladderGaps(existing: number[], added: number[]): number[] {
  const all = new Set([...existing, ...added]);
  const max = Math.max(0, ...all);
  const gaps: number[] = [];
  for (let n = 1; n <= max; n++) if (!all.has(n)) gaps.push(n);
  return gaps;
}
