// The twenty over-packed WORD_SEARCH rungs that prisma/redistribute-word-search.ts
// spreads across more grids, and the tail sequences the leftovers live in.
//
// ONE manifest, read by two scripts that must agree:
//
//  · prisma/redistribute-word-search.ts writes these rows (the data PR).
//  · prisma/generate-word-games.ts must NOT overwrite them on its next
//    full run, and must not delete the tail as "stale" either — its
//    cleanup pass deletes every sequence past the ladder's computed max,
//    and the tail is by construction past it.
//
// Why the rungs are pinned here rather than recomputed as "the worst ten"
// at run time: the redistribution runs against production, and a list
// that recomputes itself is a list nobody can review before it writes.
// The numbers below were measured ON PRODUCTION on 2026-09-02 by
// prisma/build-density-manifest.ts — see PROGRESS.md 7.83.
//
// Every entry is a PAID rung (sequence > 10) on purpose. The free rungs
// 1-10 are themed (topics.ts) and are the ones in sitemap.xml; splitting a
// themed rung would break the promise its title makes, and the tail rungs
// are all far past 10, so isFreeWordGamePuzzle stays exactly as it was and
// no new URL enters the sitemap.
import type { FlashcardLevel } from "@/lib/flashcards/types";

export interface DensitySplit {
  level: FlashcardLevel;
  /** The rung that is over-packed. Regenerated IN PLACE — same row id,
   * same URL, same WordGameProgress. */
  sequence: number;
  /** Total grids the words end up in, including the one above. */
  parts: number;
  /** Where the leftover parts go: `parts - 1` new rungs at the tail of
   * this level's WORD_SEARCH ladder. */
  tailSequences: number[];
}

/**
 * Worst-first by the severity in density.ts, MEASURED ON PRODUCTION
 * (2026-09-02) — not on dev.db.
 *
 * The previous twenty were measured on the local copy, and the local copy
 * turned out to hold a different bank under the same rung numbers: 1691
 * of 1738 word lists differ, no id is shared, and crosswords differ just
 * as hard (30 of 1262 match). The cause is in the generator, and it is
 * fixed in the same PR as this list — `flashcardCard.findMany` read cards
 * without `orderBy`, so the pool arrived in rowid order, and a seeded
 * shuffle over a differently ordered pool picks different words. See
 * PROGRESS.md 7.83.
 *
 * Production is the reference copy, so this list is what production
 * actually needs. Regenerated by `npm run db:build-density-manifest` run
 * against production; `parts` is what the packer achieved on the real
 * rows, not a number copied from the old file — every one of these twenty
 * splits into exactly 2 grids, where the local list demanded 3 for five
 * of them. Selection rule: src/lib/word-games/rung-class.ts. Nothing was
 * displaced by the placement class this round (0 rungs).
 *
 * Every entry is still a PAID rung. C1/10 looks free at a glance and is
 * not: the free rule is `level !== "C1" && sequence <= 10`, so no C1 rung
 * is ever free, and C1 has no themed-topic row in topics.ts either — its
 * title makes no category promise a split could break. isFreeWordGamePuzzle
 * is untouched and no new URL enters the sitemap.
 */
export const DENSITY_SPLITS: readonly DensitySplit[] = [
  { level: "C1", sequence: 114, parts: 2, tailSequences: [241] },
  { level: "C1", sequence: 68, parts: 2, tailSequences: [242] },
  { level: "B2", sequence: 141, parts: 2, tailSequences: [328] },
  { level: "B2", sequence: 44, parts: 2, tailSequences: [329] },
  { level: "B2", sequence: 163, parts: 2, tailSequences: [330] },
  { level: "C1", sequence: 10, parts: 2, tailSequences: [243] },
  { level: "B2", sequence: 67, parts: 2, tailSequences: [331] },
  { level: "B2", sequence: 113, parts: 2, tailSequences: [332] },
  { level: "C1", sequence: 164, parts: 2, tailSequences: [244] },
  { level: "B2", sequence: 232, parts: 2, tailSequences: [333] },

  // Второй круг. Порядок в файле и есть порядок применения: хвостовые
  // номера первого круга идут раньше, и круг 2, запущенный первым,
  // немедленно объявит дыру в лестнице (сторож ladderGaps, 7.79).
  { level: "B2", sequence: 43, parts: 2, tailSequences: [334] },
  { level: "B2", sequence: 42, parts: 2, tailSequences: [335] },
  { level: "C1", sequence: 138, parts: 2, tailSequences: [245] },
  { level: "C1", sequence: 27, parts: 2, tailSequences: [246] },
  { level: "B1", sequence: 400, parts: 2, tailSequences: [563] },
  { level: "C1", sequence: 24, parts: 2, tailSequences: [247] },
  { level: "C1", sequence: 165, parts: 2, tailSequences: [248] },
  { level: "B2", sequence: 211, parts: 2, tailSequences: [336] },
  { level: "B2", sequence: 65, parts: 2, tailSequences: [337] },
  { level: "C1", sequence: 90, parts: 2, tailSequences: [249] },
];

/** How many sequences each level's WORD_SEARCH ladder gains beyond what
 * generate-word-games.ts itself writes. */
export function densityTailCount(level: string): number {
  return DENSITY_SPLITS.filter((s) => s.level === level).reduce((n, s) => n + s.tailSequences.length, 0);
}

/** True for a rung the redistribution owns — either a split source or one
 * of its tail rungs. generate-word-games.ts leaves both alone. */
export function isDensityOwnedRung(type: string, level: string, sequence: number): boolean {
  if (type !== "WORD_SEARCH") return false;
  return DENSITY_SPLITS.some(
    (s) => s.level === level && (s.sequence === sequence || s.tailSequences.includes(sequence)),
  );
}

export function findDensitySplit(level: string, sequence: number): DensitySplit | undefined {
  return DENSITY_SPLITS.find((s) => s.level === level && s.sequence === sequence);
}

/** Every tail sequence the manifest will create on one level, ascending. */
export function densityTails(level: string): number[] {
  return DENSITY_SPLITS.filter((s) => s.level === level)
    .flatMap((s) => s.tailSequences)
    .sort((a, b) => a - b);
}

/** Levels the manifest touches at all. */
export function densityLevels(): string[] {
  return [...new Set(DENSITY_SPLITS.map((s) => s.level))].sort();
}

/**
 * Why a gap in the ladder is a defect and not a cosmetic complaint.
 *
 * WordGamesPicker renders `Array.from({length: total}, (_, i) => i + 1)` —
 * it asks the database how MANY rows a (type, level) pair has and then
 * links sequences 1…count. It never asks WHICH sequences exist. So a
 * ladder of 333 rows numbered 1…332 plus 340 renders links 1…333: the
 * row at 340 is unreachable, and 333 is a link to a 404. Both halves of
 * that are silent — nothing throws, nothing logs.
 *
 * Every level's WORD_SEARCH ladder is contiguous 1…N today (verified over
 * all 1738 rows of the 2026-09-01 baseline), and the redistribution is
 * the first thing that ever appends rows by hand, so it is the first
 * thing that can break it. Hence this: given the sequences a level
 * already has plus the ones the manifest would add, the union must still
 * be exactly 1…N.
 */
export function ladderGaps(existing: number[], added: number[]): number[] {
  const all = new Set([...existing, ...added]);
  const max = Math.max(0, ...all);
  const gaps: number[] = [];
  for (let n = 1; n <= max; n++) if (!all.has(n)) gaps.push(n);
  return gaps;
}
