// The twenty over-packed WORD_SEARCH rungs that prisma/redistribute-word-search.ts
// spreads across more grids, and the tail sequences the leftovers live in.
//
// ONE manifest, read by two scripts that must agree:
//
//  · prisma/redistribute-word-search.ts writes these rows (the data PR).
//  · prisma/generate-word-games.ts must NOT overwrite them on its next
//    full run, and must not delete the tail as "stale" either — its
//    cleanup pass deletes every sequence past the ladder's computed max,
//    and the tail is by construction past it.
//
// Why the rungs are pinned here rather than recomputed as "the worst ten"
// at run time: the redistribution runs against production, and a list
// that recomputes itself is a list nobody can review before it writes.
// The numbers below were measured ON PRODUCTION on 2026-09-02 by
// prisma/build-density-manifest.ts — see PROGRESS.md 7.83.
//
// Every entry is a PAID rung (sequence > 10) on purpose. The free rungs
// 1-10 are themed (topics.ts) and are the ones in sitemap.xml; splitting a
// themed rung would break the promise its title makes, and the tail rungs
// are all far past 10, so isFreeWordGamePuzzle stays exactly as it was and
// no new URL enters the sitemap.
import type { FlashcardLevel } from "@/lib/flashcards/types";

export interface DensitySplit {
  level: FlashcardLevel;
  /** The rung that is over-packed. Regenerated IN PLACE — same row id,
   * same URL, same WordGameProgress. */
  sequence: number;
  /** Total grids the words end up in, including the one above. */
  parts: number;
  /** Стороны сеток, по одной на часть, в том же порядке: первая — сторона
   * строки-источника, остальные — хвостовых строк. Размер доски теперь
   * ВЫБИРАЕТСЯ под длину слов и целевую занятость (quality.ts), а не
   * наследуется, поэтому он часть манифеста: то, что показано до записи,
   * и есть то, что записывается — планировщик обязан прийти к этим же
   * сторонам, иначе прогон останавливается. */
  sizes: number[];
  /** Where the leftover parts go: `parts - 1` new rungs at the tail of
   * this level's WORD_SEARCH ladder. */
  tailSequences: number[];
  /**
   * Дата, когда запись УЖЕ применена к проду. Такие строки остаются в
   * манифесте навсегда и не удаляются: на них держится
   * `isDensityOwnedRung`, а на нём — защита хвостовых строк от чистки
   * `generate-word-games.ts` (она удаляет всё, что старше расчётного
   * максимума лестницы, а хвост по построению именно там).
   *
   * По умолчанию прогон разгрузки их пропускает: их источники уже в
   * коридоре, и повторная раскладка либо ничего не даст, либо разойдётся
   * с числом частей манифеста.
   */
  applied?: string;
}

/**
 * Worst-first by the severity in density.ts, MEASURED ON PRODUCTION
 * (2026-09-02) — not on dev.db.
 *
 * The previous twenty were measured on the local copy, and the local copy
 * turned out to hold a different bank under the same rung numbers: 1691
 * of 1738 word lists differ, no id is shared, and crosswords differ just
 * as hard (30 of 1262 match). The cause is in the generator, and it is
 * fixed in the same PR as this list — `flashcardCard.findMany` read cards
 * without `orderBy`, so the pool arrived in rowid order, and a seeded
 * shuffle over a differently ordered pool picks different words. See
 * PROGRESS.md 7.83.
 *
 * Production is the reference copy, so this list is what production
 * actually needs. Regenerated by `npm run db:build-density-manifest` run
 * against production; `parts` is what the packer achieved on the real
 * rows, not a number copied from the old file — every one of these twenty
 * splits into exactly 2 grids, where the local list demanded 3 for five
 * of them. Selection rule: src/lib/word-games/rung-class.ts. Nothing was
 * displaced by the placement class this round (0 rungs).
 *
 * Every entry is still a PAID rung. C1/10 looks free at a glance and is
 * not: the free rule is `level !== "C1" && sequence <= 10`, so no C1 rung
 * is ever free, and C1 has no themed-topic row in topics.ts either — its
 * title makes no category promise a split could break. isFreeWordGamePuzzle
 * is untouched and no new URL enters the sitemap.
 */
export const DENSITY_SPLITS: readonly DensitySplit[] = [
  { level: "C1", sequence: 114, parts: 2, sizes: [16, 16], tailSequences: [241], applied: "2026-09-02" },
  { level: "C1", sequence: 68, parts: 2, sizes: [16, 16], tailSequences: [242], applied: "2026-09-02" },
  { level: "B2", sequence: 141, parts: 2, sizes: [16, 16], tailSequences: [328], applied: "2026-09-02" },
  { level: "B2", sequence: 44, parts: 2, sizes: [16, 16], tailSequences: [329], applied: "2026-09-02" },
  { level: "B2", sequence: 163, parts: 2, sizes: [16, 16], tailSequences: [330], applied: "2026-09-02" },
  { level: "C1", sequence: 10, parts: 2, sizes: [16, 16], tailSequences: [243], applied: "2026-09-02" },
  { level: "B2", sequence: 67, parts: 2, sizes: [16, 16], tailSequences: [331], applied: "2026-09-02" },
  { level: "B2", sequence: 113, parts: 2, sizes: [16, 16], tailSequences: [332], applied: "2026-09-02" },
  { level: "C1", sequence: 164, parts: 2, sizes: [16, 16], tailSequences: [244], applied: "2026-09-02" },
  { level: "B2", sequence: 232, parts: 2, sizes: [16, 16], tailSequences: [333], applied: "2026-09-02" },

  // Второй круг. Порядок в файле и есть порядок применения: хвостовые
  // номера первого круга идут раньше, и круг 2, запущенный первым,
  // немедленно объявит дыру в лестнице (сторож ladderGaps, 7.79).
  { level: "B2", sequence: 43, parts: 2, sizes: [16, 16], tailSequences: [334], applied: "2026-09-02" },
  { level: "B2", sequence: 42, parts: 2, sizes: [16, 16], tailSequences: [335], applied: "2026-09-02" },
  { level: "C1", sequence: 138, parts: 2, sizes: [16, 16], tailSequences: [245], applied: "2026-09-02" },
  { level: "C1", sequence: 27, parts: 2, sizes: [16, 16], tailSequences: [246], applied: "2026-09-02" },
  { level: "B1", sequence: 400, parts: 2, sizes: [16, 16], tailSequences: [563], applied: "2026-09-02" },
  { level: "C1", sequence: 24, parts: 2, sizes: [16, 16], tailSequences: [247], applied: "2026-09-02" },
  { level: "C1", sequence: 165, parts: 2, sizes: [16, 16], tailSequences: [248], applied: "2026-09-02" },
  { level: "B2", sequence: 211, parts: 2, sizes: [16, 16], tailSequences: [336], applied: "2026-09-02" },
  { level: "B2", sequence: 65, parts: 2, sizes: [16, 16], tailSequences: [337], applied: "2026-09-02" },
  { level: "C1", sequence: 90, parts: 2, sizes: [16, 16], tailSequences: [249], applied: "2026-09-02" },

  // ── Круг 3 (02.09.2026), сорок рунгов. Отобран УЖЕ ПО КОРИДОРУ quality.ts, а не
  // только по порогу density.ts: сорок худших по тяжести из тех, кого
  // новое правило действительно приводит в коридор. Четверых пришлось
  // пропустить — их лучший достижимый план всё равно вне коридора
  // (B2/9 → 18×18 78,1%; B2/230 → 14+18 47,4/43,8%; C1/122 → 18×18 71,6%;
  // B1/14 → 18×18 71,0%), их места заняли следующие по тяжести.
  //
  // Здесь впервые появляются РАЗНЫЕ стороны: `sizes` — это выбор
  // планировщика под длину слов и целевую занятость, а не сторона
  // источника. Два рунга (A2/162 и B2/49) чинятся ОДНОЙ сменой размера:
  // parts: 1, новых строк ноль.
  { level: "C1", sequence: 140, parts: 2, sizes: [14, 18], tailSequences: [250], applied: "2026-09-02" },
  { level: "B2", sequence: 139, parts: 2, sizes: [16, 18], tailSequences: [338], applied: "2026-09-02" },
  { level: "C1", sequence: 69, parts: 2, sizes: [14, 18], tailSequences: [251], applied: "2026-09-02" },
  { level: "C1", sequence: 70, parts: 2, sizes: [14, 18], tailSequences: [252], applied: "2026-09-02" },
  { level: "C1", sequence: 9, parts: 2, sizes: [14, 18], tailSequences: [253], applied: "2026-09-02" },
  { level: "B2", sequence: 17, parts: 2, sizes: [14, 18], tailSequences: [339], applied: "2026-09-02" },
  { level: "B2", sequence: 209, parts: 2, sizes: [14, 18], tailSequences: [340], applied: "2026-09-02" },
  { level: "C1", sequence: 166, parts: 2, sizes: [14, 18], tailSequences: [254], applied: "2026-09-02" },
  { level: "B1", sequence: 67, parts: 2, sizes: [14, 18], tailSequences: [564], applied: "2026-09-02" },
  { level: "B2", sequence: 164, parts: 2, sizes: [16, 16], tailSequences: [341], applied: "2026-09-02" },
  { level: "B2", sequence: 236, parts: 2, sizes: [14, 18], tailSequences: [342], applied: "2026-09-02" },
  { level: "B2", sequence: 41, parts: 2, sizes: [12, 18], tailSequences: [343], applied: "2026-09-02" },
  { level: "C1", sequence: 12, parts: 2, sizes: [14, 18], tailSequences: [255], applied: "2026-09-02" },
  { level: "C1", sequence: 143, parts: 2, sizes: [12, 18], tailSequences: [256], applied: "2026-09-02" },
  { level: "B1", sequence: 259, parts: 2, sizes: [14, 18], tailSequences: [565], applied: "2026-09-02" },
  { level: "B1", sequence: 306, parts: 2, sizes: [14, 18], tailSequences: [566], applied: "2026-09-02" },
  { level: "B2", sequence: 165, parts: 2, sizes: [14, 18], tailSequences: [344], applied: "2026-09-02" },
  { level: "B1", sequence: 188, parts: 2, sizes: [14, 18], tailSequences: [567], applied: "2026-09-02" },
  { level: "B1", sequence: 355, parts: 2, sizes: [14, 18], tailSequences: [568], applied: "2026-09-02" },
  { level: "C1", sequence: 135, parts: 2, sizes: [14, 18], tailSequences: [257], applied: "2026-09-02" },
  { level: "C1", sequence: 118, parts: 2, sizes: [14, 18], tailSequences: [258], applied: "2026-09-02" },
  { level: "C1", sequence: 46, parts: 2, sizes: [14, 18], tailSequences: [259], applied: "2026-09-02" },
  { level: "B2", sequence: 38, parts: 2, sizes: [10, 18], tailSequences: [345], applied: "2026-09-02" },
  { level: "A2", sequence: 162, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-02" },
  { level: "C1", sequence: 116, parts: 2, sizes: [14, 18], tailSequences: [260], applied: "2026-09-02" },
  { level: "B2", sequence: 136, parts: 2, sizes: [14, 18], tailSequences: [346], applied: "2026-09-02" },
  { level: "C1", sequence: 160, parts: 2, sizes: [14, 18], tailSequences: [261], applied: "2026-09-02" },
  { level: "C1", sequence: 93, parts: 2, sizes: [14, 18], tailSequences: [262], applied: "2026-09-02" },
  { level: "C1", sequence: 14, parts: 2, sizes: [10, 18], tailSequences: [263], applied: "2026-09-02" },
  { level: "B2", sequence: 162, parts: 2, sizes: [14, 18], tailSequences: [347], applied: "2026-09-02" },
  { level: "C1", sequence: 162, parts: 2, sizes: [14, 18], tailSequences: [264], applied: "2026-09-02" },
  { level: "B2", sequence: 116, parts: 2, sizes: [14, 18], tailSequences: [348], applied: "2026-09-02" },
  { level: "B2", sequence: 210, parts: 2, sizes: [14, 18], tailSequences: [349], applied: "2026-09-02" },
  { level: "B1", sequence: 282, parts: 2, sizes: [14, 18], tailSequences: [569], applied: "2026-09-02" },
  { level: "B1", sequence: 356, parts: 2, sizes: [12, 18], tailSequences: [570], applied: "2026-09-02" },
  { level: "C1", sequence: 67, parts: 2, sizes: [12, 18], tailSequences: [265], applied: "2026-09-02" },
  { level: "C1", sequence: 40, parts: 2, sizes: [12, 18], tailSequences: [266], applied: "2026-09-02" },
  { level: "B2", sequence: 49, parts: 1, sizes: [18], tailSequences: [], applied: "2026-09-02" },
  { level: "B1", sequence: 238, parts: 2, sizes: [12, 18], tailSequences: [571], applied: "2026-09-02" },
  { level: "C1", sequence: 47, parts: 2, sizes: [12, 18], tailSequences: [267], applied: "2026-09-02" },
];

/** How many sequences each level's WORD_SEARCH ladder gains beyond what
 * generate-word-games.ts itself writes. */
export function densityTailCount(level: string): number {
  return DENSITY_SPLITS.filter((s) => s.level === level).reduce((n, s) => n + s.tailSequences.length, 0);
}

/** True for a rung the redistribution owns — either a split source or one
 * of its tail rungs. generate-word-games.ts leaves both alone. */
export function isDensityOwnedRung(type: string, level: string, sequence: number): boolean {
  if (type !== "WORD_SEARCH") return false;
  return DENSITY_SPLITS.some(
    (s) => s.level === level && (s.sequence === sequence || s.tailSequences.includes(sequence)),
  );
}

export function findDensitySplit(level: string, sequence: number): DensitySplit | undefined {
  return DENSITY_SPLITS.find((s) => s.level === level && s.sequence === sequence);
}

/** Every tail sequence the manifest will create on one level, ascending. */
export function densityTails(level: string): number[] {
  return DENSITY_SPLITS.filter((s) => s.level === level)
    .flatMap((s) => s.tailSequences)
    .sort((a, b) => a - b);
}

/** Levels the manifest touches at all. */
export function densityLevels(): string[] {
  return [...new Set(DENSITY_SPLITS.map((s) => s.level))].sort();
}

/**
 * Why a gap in the ladder is a defect and not a cosmetic complaint.
 *
 * WordGamesPicker renders `Array.from({length: total}, (_, i) => i + 1)` —
 * it asks the database how MANY rows a (type, level) pair has and then
 * links sequences 1…count. It never asks WHICH sequences exist. So a
 * ladder of 333 rows numbered 1…332 plus 340 renders links 1…333: the
 * row at 340 is unreachable, and 333 is a link to a 404. Both halves of
 * that are silent — nothing throws, nothing logs.
 *
 * Every level's WORD_SEARCH ladder is contiguous 1…N today (verified over
 * all 1738 rows of the 2026-09-01 baseline), and the redistribution is
 * the first thing that ever appends rows by hand, so it is the first
 * thing that can break it. Hence this: given the sequences a level
 * already has plus the ones the manifest would add, the union must still
 * be exactly 1…N.
 */
export function ladderGaps(existing: number[], added: number[]): number[] {
  const all = new Set([...existing, ...added]);
  const max = Math.max(0, ...all);
  const gaps: number[] = [];
  for (let n = 1; n <= max; n++) if (!all.has(n)) gaps.push(n);
  return gaps;
}
