import type { VideoLessonData } from "./types";

export const sampleLesson: VideoLessonData = {
  id: "gagarin-1961",
  title: "Юрий Гагарин: первый полёт в космос",
  youtubeVideoId: "9YMU2wmSj0U",
  level: "A2",
  subtitles: [
    {
      id: "s1",
      start: 0,
      end: 4,
      ru: "Двенадцатого апреля тысяча девятьсот шестьдесят первого года",
      es: "El doce de abril de mil novecientos sesenta y uno",
    },
    {
      id: "s2",
      start: 4,
      end: 8,
      ru: "человек впервые полетел в космос.",
      es: "el hombre voló al espacio por primera vez.",
    },
    {
      id: "s3",
      start: 8,
      end: 13,
      ru: "Этим человеком был советский космонавт Юрий Гагарин.",
      es: "Ese hombre fue el cosmonauta soviético Yuri Gagarin.",
    },
    {
      id: "s4",
      start: 13,
      end: 18,
      ru: "Полёт корабля «Восток-1» продолжался сто восемь минут.",
      es: "El vuelo de la nave «Vostok-1» duró ciento ocho minutos.",
    },
    {
      id: "s5",
      start: 18,
      end: 23,
      ru: "После посадки вся страна встречала героя с радостью.",
      es: "Tras el aterrizaje, todo el país recibió al héroe con alegría.",
    },
  ],
  glossary: {
    человек: {
      lemma: "человек",
      translation: "hombre, persona",
      partOfSpeech: "sustantivo",
      grammarNote: "caso nominativo, singular",
    },
    впервые: {
      lemma: "впервые",
      translation: "por primera vez",
      partOfSpeech: "adverbio",
    },
    полетел: {
      lemma: "полететь",
      translation: "voló, echó a volar",
      partOfSpeech: "verbo",
      grammarNote: "pasado, aspecto perfectivo, masculino singular",
    },
    космос: {
      lemma: "космос",
      translation: "espacio (cósmico)",
      partOfSpeech: "sustantivo",
      grammarNote: "caso acusativo tras «в», singular",
    },
    советский: {
      lemma: "советский",
      translation: "soviético",
      partOfSpeech: "adjetivo",
    },
    космонавт: {
      lemma: "космонавт",
      translation: "cosmonauta",
      partOfSpeech: "sustantivo",
    },
    полёт: {
      lemma: "полёт",
      translation: "vuelo",
      partOfSpeech: "sustantivo",
    },
    продолжался: {
      lemma: "продолжаться",
      translation: "duró, se prolongó",
      partOfSpeech: "verbo",
      grammarNote: "pasado, aspecto imperfectivo, masculino singular",
    },
    посадки: {
      lemma: "посадка",
      translation: "aterrizaje",
      partOfSpeech: "sustantivo",
      grammarNote: "caso genitivo tras «после», singular",
    },
    страна: {
      lemma: "страна",
      translation: "país",
      partOfSpeech: "sustantivo",
    },
    героя: {
      lemma: "герой",
      translation: "héroe",
      partOfSpeech: "sustantivo",
      grammarNote: "caso винительный (acusativo animado), singular",
    },
    радостью: {
      lemma: "радость",
      translation: "alegría",
      partOfSpeech: "sustantivo",
      grammarNote: "caso instrumental tras «с», singular",
    },
  },
  historicalContext: [
    {
      id: "epoca",
      title: "La era espacial y la Guerra Fría",
      bodyEs:
        "El vuelo de Gagarin ocurrió en plena Guerra Fría, en el contexto de la carrera espacial entre la URSS y Estados Unidos. Cuatro años antes, en 1957, la URSS ya había lanzado el Sputnik 1, el primer satélite artificial de la historia.\n\nEl éxito de la misión Vostok 1 se convirtió en un símbolo de propaganda para el bloque soviético, presentado como prueba de la superioridad del sistema socialista en ciencia y tecnología.",
    },
    {
      id: "gagarin",
      title: "¿Quién fue Yuri Gagarin?",
      bodyEs:
        "Yuri Alekséyevich Gagarin (1934–1968) fue un piloto militar soviético seleccionado entre miles de candidatos para el primer vuelo tripulado al espacio. Tras su histórico vuelo se convirtió instantáneamente en un héroe nacional e ícono mundial.\n\nMurió en 1968 durante un vuelo de entrenamiento rutinario, a los 34 años, lo que añadió un aire trágico a su legado.",
    },
    {
      id: "legado",
      title: "Legado cultural",
      bodyEs:
        "La frase atribuida a Gagarin al despegar, «¡Poyejali!» («¡Vamos!»), se convirtió en una expresión popular en ruso, usada hasta hoy para expresar el inicio entusiasta de cualquier empresa.\n\nEl 12 de abril se celebra en Rusia y otros países el Día de la Cosmonáutica en su honor.",
    },
  ],
  vocabulary: [
    {
      id: "v1",
      word: "космос",
      translation: "espacio (cósmico)",
      partOfSpeech: "sustantivo",
      exampleRu: "Человек впервые полетел в космос.",
      exampleEs: "El hombre voló al espacio por primera vez.",
    },
    {
      id: "v2",
      word: "космонавт",
      translation: "cosmonauta",
      partOfSpeech: "sustantivo",
      exampleRu: "Этим человеком был советский космонавт Юрий Гагарин.",
      exampleEs: "Ese hombre fue el cosmonauta soviético Yuri Gagarin.",
    },
    {
      id: "v3",
      word: "полететь",
      translation: "echar a volar, volar (perfectivo)",
      partOfSpeech: "verbo",
      exampleRu: "Человек впервые полетел в космос.",
      exampleEs: "El hombre voló al espacio por primera vez.",
    },
    {
      id: "v4",
      word: "полёт",
      translation: "vuelo",
      partOfSpeech: "sustantivo",
      exampleRu: "Полёт корабля «Восток-1» продолжался сто восемь минут.",
      exampleEs: "El vuelo de la nave «Vostok-1» duró ciento ocho minutos.",
    },
    {
      id: "v5",
      word: "корабль",
      translation: "nave, barco",
      partOfSpeech: "sustantivo",
      exampleRu: "Полёт корабля «Восток-1» продолжался сто восемь минут.",
      exampleEs: "El vuelo de la nave «Vostok-1» duró ciento ocho minutos.",
    },
    {
      id: "v6",
      word: "продолжаться",
      translation: "durar, prolongarse",
      partOfSpeech: "verbo",
      exampleRu: "Полёт продолжался сто восемь минут.",
      exampleEs: "El vuelo duró ciento ocho minutos.",
    },
    {
      id: "v7",
      word: "посадка",
      translation: "aterrizaje",
      partOfSpeech: "sustantivo",
      exampleRu: "После посадки вся страна встречала героя с радостью.",
      exampleEs: "Tras el aterrizaje, todo el país recibió al héroe con alegría.",
    },
    {
      id: "v8",
      word: "герой",
      translation: "héroe",
      partOfSpeech: "sustantivo",
      exampleRu: "Вся страна встречала героя с радостью.",
      exampleEs: "Todo el país recibió al héroe con alegría.",
    },
    {
      id: "v9",
      word: "радость",
      translation: "alegría",
      partOfSpeech: "sustantivo",
      exampleRu: "Вся страна встречала героя с радостью.",
      exampleEs: "Todo el país recibió al héroe con alegría.",
    },
    {
      id: "v10",
      word: "впервые",
      translation: "por primera vez",
      partOfSpeech: "adverbio",
      exampleRu: "Человек впервые полетел в космос.",
      exampleEs: "El hombre voló al espacio por primera vez.",
    },
  ],
  quiz: [
    {
      id: "q1",
      section: "contexto",
      prompt: "¿En qué contexto histórico ocurrió el vuelo de Gagarin?",
      options: [
        { id: "a", text: "La Segunda Guerra Mundial" },
        { id: "b", text: "La carrera espacial de la Guerra Fría" },
        { id: "c", text: "La Revolución rusa" },
      ],
      correctOptionId: "b",
      explanationEs: "El vuelo de 1961 fue un hito clave de la carrera espacial entre la URSS y EE. UU.",
    },
    {
      id: "q2",
      section: "contexto",
      prompt: "¿Qué satélite lanzó la URSS antes del vuelo de Gagarin?",
      options: [
        { id: "a", text: "Sputnik 1" },
        { id: "b", text: "Vostok 1" },
        { id: "c", text: "Soyuz 1" },
      ],
      correctOptionId: "a",
      explanationEs: "El Sputnik 1, lanzado en 1957, fue el primer satélite artificial de la historia.",
    },
    {
      id: "q3",
      section: "contexto",
      prompt: "¿Qué frase de Gagarin se volvió una expresión popular en ruso?",
      options: [
        { id: "a", text: "«Спасибо» (Gracias)" },
        { id: "b", text: "«Поехали!» (¡Vamos!)" },
        { id: "c", text: "«До свидания» (Adiós)" },
      ],
      correctOptionId: "b",
      explanationEs: "«Поехали!» se usa hoy en día para expresar el inicio entusiasta de una empresa.",
    },
    {
      id: "q4",
      section: "vocabulario",
      prompt: "«Космонавт» significa...",
      options: [
        { id: "a", text: "astrónomo" },
        { id: "b", text: "cosmonauta" },
        { id: "c", text: "piloto de avión" },
      ],
      correctOptionId: "b",
    },
    {
      id: "q5",
      section: "vocabulario",
      prompt: "Completa: «Человек ___ полетел в космос» (por primera vez)",
      options: [
        { id: "a", text: "впервые" },
        { id: "b", text: "всегда" },
        { id: "c", text: "иногда" },
      ],
      correctOptionId: "a",
    },
    {
      id: "q6",
      section: "vocabulario",
      prompt: "«Посадка» se traduce como...",
      options: [
        { id: "a", text: "despegue" },
        { id: "b", text: "aterrizaje" },
        { id: "c", text: "vuelo" },
      ],
      correctOptionId: "b",
    },
    {
      id: "q7",
      section: "vocabulario",
      prompt: "¿Cuál es el verbo relacionado con «полёт» (vuelo)?",
      options: [
        { id: "a", text: "летать / полететь" },
        { id: "b", text: "ходить / пойти" },
        { id: "c", text: "смотреть / посмотреть" },
      ],
      correctOptionId: "a",
    },
  ],
};
